linuxdeepin/deepin-screen-recorder

- deepin-screen-recorder.desktop
Correct the zh_TW translation.
> Correct the zh_TW translation.

- src/record_process.cpp
Append crf paramter of ffmpeg in src/record_process.cpp. 
Submitted by Research Group of Zhenzhong Chen from Wuhan University.
> update src/record_process.cpp. 

- src/main_window.cpp
> refactor: Can't select window correctly

- src/main_window.cpp
- src/start_tooltip.cpp
https://github.com/linuxdeepin/qt5dxcb-plugin/pull/17
> fix: cannot select window on other screen

- com.deepin.ScreenRecorder.service
- com.deepin.Screenshot.service
- deepin-screen-recorder.desktop
- deepin-screenshot
- deepin-screenshot.desktop
- screen_shot_recorder.pro
- src/event_monitor.cpp
- src/main.cpp
- src/screen_shot_event.cpp
- src/utils.cpp
- src/widgets/shapeswidget.cpp
- src/widgets/tooltips.cpp
> perf: add turbo and wrapper

- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- tests/test-prj-running.sh
- tests/ut_dde_dock_plugins/build_run_ut.sh
- tests/ut_dde_dock_plugins/ut_dde_dock_plugins.pro
- tests/ut_dde_dock_plugins/ut_shot_start/build_run_ut.sh
- tests/ut_dde_dock_plugins/ut_shot_start/main.cpp
- tests/ut_dde_dock_plugins/ut_shot_start/ut_iconwidget.cpp
- tests/ut_dde_dock_plugins/ut_shot_start/ut_mock_pluginproxyinterface.h
- tests/ut_dde_dock_plugins/ut_shot_start/ut_shot_start.pro
- tests/ut_dde_dock_plugins/ut_shot_start/ut_shotstartplugin.cpp
- tests/ut_dde_dock_plugins/ut_shot_start/ut_tipswidget.cpp
> chore: unit test

- deepin-screen-recorder.desktop
Fixes desktop-entry-lacks-keywords-entry lintian error.
> Add Keywords in desktop file.

- src/main_window.cpp
- src/widgets/subtoolwidget.cpp
- src/widgets/subtoolwidget.h
- src/widgets/toolbar.cpp
- src/widgets/toolbar.h
feat: 锁屏界面屏蔽相关功能
锁屏界面屏蔽，文字编辑，OCR，滚动截图，贴图，选项
Log: 锁屏界面特殊性，功能有冲突
Task: https://pms.uniontech.com/task-view-118843.html
Influence: 锁屏与截图录屏的交互
> 锁屏界面屏蔽相关功能

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- src/gstrecord/gstrecordx.cpp
- src/gstrecord/gstrecordx.h
- src/record_process.cpp
- src/waylandrecord/recordadmin.cpp
- tests/ut_dde_dock_plugins/ut_shot_start/ut_tipswidget.cpp
- tests/ut_screen_shot_recorder/ut_record_process.h
Description: 修复arm内存泄漏
Log: 修复arm内存泄漏
> chore: 修复arm内存泄漏

- src/gstrecord/gstrecordx.cpp
- src/gstrecord/gstrecordx.h
- src/waylandrecord/waylandintegration.cpp
Description: hw主板采集的像素格式不同，需特别处理
Log: （wayland）gstreamer录屏适配hw机型
> chore: （wayland）gstreamer录屏适配hw机型

- src/src.pro
- tests/ut_screen_shot_recorder/ut_screen_shot_recorder.pro
Description: 更改工程文件中引用的gstreamer库名
Log: 更改工程文件中引用的gstreamer库名
> chore: 更改工程文件中引用的gstreamer库名

- src/dde-dock-plugins/shotstart/com.deepin.dde.dock.module.shot-start-plugin.gschema.xml
- src/dde-dock-plugins/shotstart/shotstart.pro
> fix: 添加配置文件

- src/record_process.cpp
- src/waylandrecord/avinputstream.cpp
- src/waylandrecord/avinputstream.h
- src/waylandrecord/recordadmin.cpp
- src/waylandrecord/recordadmin.h
Description: 由于麦克风声卡的设备名称有误
Log: 修复插入USB耳机，录制视频后，未保存录制的视频
Bug: https://pms.uniontech.com/bug-view-130441.html
> fix: 修复插入USB耳机，录制视频后，未保存录制的视频

- debian/control
Description: 删除库依赖
Log: 删除private库依赖
> feat(截图录屏): 兼容性

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- src/dde-dock-plugins/recordtime/recordtimeplugin.h
Description: 由于录屏图标界面未被释放
Log: 修复拖动托盘录屏图标至任务栏外后,系统窗口左上角显示录屏图标
Bug: https://pms.uniontech.com/bug-view-129833.html
> fix: 修复拖动托盘录屏图标至任务栏外后,系统窗口左上角显示录屏图标

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- tests/ut_dde_dock_plugins/ut_record_time/ut_mock_stub_recordtimeplugin.cpp
Description: 修复ci问题
Log: 修复ci问题
> chore: 修复ci问题

- src/main_window.cpp
- src/pin_screenshots/mainwindow.cpp
Description: 根据屏幕宽度适配工具栏位置x值
Log: https://pms.uniontech.com/bug-view-133823.html
> fix(贴图): 贴图工具栏位置适应

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- tests/ut_dde_dock_plugins/ut_record_time/ut_mock_stub_recordtimeplugin.cpp
Description: 修复内存泄漏
Log: 修复内存泄漏
> chore: 修复内存泄漏

- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
Description: 更改判断华为机型的方式
Log: 更改判断华为机型的方式
> chore: 更改判断华为机型的方式

- src/gstrecord/gstinterface.cpp
- src/gstrecord/gstinterface.h
- src/gstrecord/gstrecordx.cpp
- src/gstrecord/gstrecordx.h
- src/record_process.cpp
- src/src.pro
- tests/ut_screen_shot_recorder/gstrecord/ut_gstrecordx.h
- tests/ut_screen_shot_recorder/ut_screen_shot_recorder.pro
Description: 将gstreamer加载方式改为动态加载
Log: 将gstreamer加载方式改为动态加载
Taks:  https://pms.uniontech.com/task-view-138763.html
> feat: 将gstreamer加载方式改为动态加载

- debian/control
Description: 添加gstreamer的依赖
Log: 添加gstreamer的依赖
> chore: 添加gstreamer的依赖

- debian/control
- src/main_window.cpp
- src/widgets/camerawidget.cpp
- src/widgets/shapeswidget.cpp
Description: 由于QCamera中会使用该库
Log:  添加gstreamer1.0-plugins-bad库的强依赖
Bug: https://pms.uniontech.com/bug-view-142517.html
> fix: 添加gstreamer1.0-plugins-bad库的强依赖 

- debian/control
- src/button_feedback.cpp
- src/main.cpp
- src/main_window.cpp
- src/record_process.cpp
- src/utils.cpp
- src/utils.h
- src/utils/audioutils.cpp
- src/waylandrecord/avinputstream.cpp
- src/waylandrecord/recordadmin.cpp
- src/widgets/camerawidget.cpp
- src/widgets/shapeswidget.cpp
- src/widgets/zoomIndicator.cpp
> 将master分支的代码同步到maintain/v20

- src/main_window.cpp
- src/utils.cpp
- src/widgets/zoomIndicator.cpp
- src/widgets/zoomIndicator.h
Description: 由于该条件下缩放比例计算有误
Log: 修复双屏1.25倍缩放下，截图放大镜位置错误及显示错误
Bug: https://pms.uniontech.com/bug-view-142133.html
> fix: 修复双屏1.25倍缩放下，截图放大镜位置错误及显示错误

- src/pin_screenshots/main.cpp
- src/pin_screenshots/mainwindow.cpp
- src/pin_screenshots/pin_screenshots.pro
- src/pin_screenshots/putils.cpp
- src/pin_screenshots/putils.h
- src/pin_screenshots/ui/toolbar.cpp
- src/pin_screenshots/ui/toolbarwidget.cpp
- src/pin_screenshots/utils.cpp
- src/utils/voicevolumewatcher.cpp
Description:  修复新版cppcheck错误
Log:  修复新版cppcheck错误
> fix:  修复新版cppcheck错误

- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/dde-dock-plugins/shotstart/iconwidget.h
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/utils/shortcut.cpp
- src/utils/shortcut.h
Description: 快捷键提示优化
Log: https://pms.uniontech.com/task-view-152945.html
> feat(截图录屏): 快捷键提示动态获取系统快捷键

- 3rdparty/libcam/libcam_v4l2core/v4l2_core.c
- src/camera/LPF_V4L2.c
- src/camera/majorimageprocessingthread.cpp
- src/widgets/camerawidget.cpp
Description:  某些摄像头设备无法正常获取摄像头界面
Log:  修复一些摄像头已知问题
> fix:  修复一些摄像头已知问题

- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/utils/shortcut.cpp
Description: 动态获取快捷键提示
Log: Bug: https://pms.uniontech.com/bug-view-147231.html
> fix(截图录屏): 快捷键提示

- src/dbusservice/dbusscreenshotservice.cpp
- src/main.cpp
- src/main_window.cpp
- src/record_process.cpp
- src/screenshot.cpp
- src/src.pro
- src/utils/eventlogutils.cpp
- src/utils/eventlogutils.h
> feat: 添加数据埋点功能实现

- debian/control
- src/main_window.cpp
Description: 保存后，不显示虚线框
Log: bug：https://pms.uniontech.com/bug-view-148045.html
> fix(截图录屏): 截图全屏截图流程优化

- src/dbusservice/dbusscreenshotservice.cpp
- src/main.cpp
- src/main_window.cpp
- src/record_process.cpp
- src/screenshot.cpp
- src/src.pro
> fix: 数据埋点 添加版本号

- src/main_window.cpp
- src/record_process.cpp
- src/record_process.h
- src/utils/configsettings.cpp
- src/utils/saveutils.h
- src/widgets/subtoolwidget.cpp
Description: 录屏保存优化功能实现
Log: 录屏保存优化功能实现
Task: https://pms.uniontech.com/task-view-169547.html
https://pms.uniontech.com/task-view-169549.html
> feat: 录屏保存优化功能实现

- src/main_window.cpp
- src/main_window.h
- src/widgets/shapeswidget.cpp
- src/widgets/shapeswidget.h
Description:  由于工具栏未及时隐藏，导致截图时截到工具栏，现已经更改截图保存方案
Log:  修复4k双屏1.25倍缩放,截图截到工具栏
Bug: https://pms.uniontech.com/bug-view-151133.html
> fix: 修复4k双屏1.25倍缩放,截图截到工具栏

- src/main_window.cpp
- src/widgets/shapeswidget.cpp
- src/widgets/shapeswidget.h
Description: 由于文字无法通过paintevent绘制
Log: 修复在截图中输入文字，点贴图按钮后，输入的文字消失了
Bug: https://pms.uniontech.com/bug-view-151571.html
> fix: 修复在截图中输入文字，点贴图按钮后，输入的文字消失了

- src/camera/LPF_V4L2.c
Description: 静态检测错误修复
Log: https://pms.uniontech.com/task-view-169509.html
> feat(截图录屏): 摄像头相关

- src/main_window.cpp
- src/record_process.cpp
- src/screenshot.cpp
暂时屏蔽除应用启动外的数据埋点
Log: 屏蔽除应用启动外的数据埋点
> fix: 屏蔽数据埋点

- src/main_window.cpp
- src/record_process.cpp
- src/screenshot.cpp
Reverts linuxdeepin/deepin-screen-recorder#182
> Revert "fix: 屏蔽数据埋点"

- src/main.cpp
- src/main_window.cpp
- src/record_process.cpp
- src/screenshot.cpp
修复使用快捷键ctrl+alt+r 启动录屏后，上报数据多传了一次启动数据&启动录屏的tid错误问题
Log: 修复使用快捷键ctrl+alt+r 启动录屏后，上报数据多传了一次启动数据&启动录屏的tid错误问题
> fix: 埋点bug修复

- src/main_window.cpp
开始截图改为点击保存按钮时
Log: 开始截图改为点击保存按钮时
> fix: 数据埋点 开始截图

- src/main_window.cpp
- src/record_process.cpp
修复录屏时文件格式获取错误问题
Log: 修复录屏时文件格式获取错误问题
> fix: 修复录屏时文件格式获取错误问题

- src/record_process.cpp
> chore: 删除多余分号

- debian/control
Description: 添加FFmpeg依赖
Log: Gif格式转换，添加FFmpeg依赖
> fix(依赖): FFmpeg依赖

- debian/control
Description: gif转换依赖FFmpeg
Log: bug:https://pms.uniontech.com/bug-view-153251.html 
> fix(依赖): 录屏依赖

- src/main_window.cpp
- src/utils.cpp
Description:  修复双屏1.25缩放比下,自动框选位置不正确
Log:  修复双屏1.25缩放比下,自动框选位置不正确
> fix: 修复双屏1.25缩放比下,自动框选位置不正确

- debian/control
Description: gif转换需要FFmpeg工具
Log: 添加强制依赖
> fix(依赖): FFmpeg改为强制依赖

- debian/control
Description: 修改为强制依赖
Log: ffmpeg 修改为强制依赖
> fix(依赖): 依赖修改

- src/main_window.cpp
Description:  未考虑到该场景，场景比较少见
Log:  优化多任务视图界面，选择截图区域卡顿的问题
Bug: https://pms.uniontech.com/bug-view-153867.html
> fix: 修复多屏下，工具栏位置不正确

- src/utils/eventlogutils.h
> fix: 修改启动tid

- src/main_window.cpp
- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
Description:  由于画面的像素格式不正确
Log:  修修复【PGV】双屏下截图录屏录制的视频，播放出来是黑屏，没有画面
Bug: https://pms.uniontech.com/bug-view-159105.html
> fix: 修复【PGV】双屏下截图录屏录制的视频，播放出来是黑屏，没有画面

- src/main_window.h
- src/src.pro
- src/utils/delaytime.cpp
- src/utils/delaytime.h
Description: 将QTimer超时监听换成线程实现
Log: 将QTimer超时监听换成线程实现
> fix: 将QTimer超时监听换成线程实现

- src/widgets/shapeswidget.cpp
- src/widgets/subtoolwidget.cpp
Description: 选项按钮与旁边的工具间距太近
Log: 选项按钮与旁边的工具间距太近
Bug: https://pms.uniontech.com/bug-view-154109.html
> fix: 修复选项按钮与旁边的工具间距太近

- src/main_window.cpp
Description: 修复滚动截图时启动ocr，识别的图片不正确
Log: 修复滚动截图时启动ocr，识别的图片不正确
> fix: 修复滚动截图时启动ocr，识别的图片不正确

- src/main_window.cpp
Description: 修复截长图，双击区域外，未响应保存截图
Log: 修复截长图，双击区域外，未响应保存截图
> fix: 修复截长图，双击区域外，未响应保存截图

- src/utils.cpp
Description: 教育版，社区版，家庭版兼容性判断
Log: 适配不同版本
> feat: 显示录制时长

- 3rdparty/libcam/libcam_encoder/mp4.c
- 3rdparty/libcam/libcam_encoder/mp4.h
- 3rdparty/libcam/load_libs.c
- 3rdparty/libcam/load_libs.h
> fix: 开源合规检查

- src/main_window.cpp
Description: 延时卡死问题
Log: 用线程来处理延时问题
> fix: 保存到剪贴板

- src/utils.cpp
Description: 根据系统版本判断区分某些功能
Log: 社区版版本判断优化
> feat: 版本判断

- src/main_window.cpp
- src/record_process.cpp
- src/record_process.h
- src/utils/configsettings.cpp
- src/utils/saveutils.h
- src/widgets/subtoolwidget.cpp
Description: u4屏蔽保存优化功能
Log: u4屏蔽保存优化功能
> chore: u4屏蔽保存优化功能

- debian/copyright
Description: 依赖库，开源协议声明
Log: GPL-2+协议说明
> feat: 开源协议说明

- src/record_process.cpp
Description: 修复arm MP4格式录屏保存不成功
Log: 修复arm MP4格式录屏保存不成功
Bug: https://pms.uniontech.com/bug-view-172577.html
> fix: 修复arm MP4格式录屏保存不成功

- src/waylandrecord/avlibinterface.cpp
- src/waylandrecord/waylandintegration.cpp
Description: 增加关键日志
Log: 增加关键日志
> chore: 增加关键日志

- src/dde-dock-plugins/recordtime/timewidget.cpp
- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/waylandrecord/avoutputstream.cpp
Description: 调整dock栏图标缩放策略
Log: 调整dock栏图标缩放策略
> chore: 调整dock栏图标缩放策略

- src/dde-dock-plugins/recordtime/timewidget.cpp
Description: 修复录屏计时图标偏移
Log: 修复录屏计时图标偏移
> fix: 修复录屏计时图标偏移

- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
Description: 任务栏插件默认不显示
Log: 任务栏插件默认不显示
Task: https://pms.uniontech.com/task-view-223321.html
> feat: 任务栏插件默认不显示

- src/main_window.cpp
Description: 修复wayland模式下，无法滚动截图
Log: 修复wayland模式下，无法滚动截图
Bug: https://pms.uniontech.com/bug-view-178451.html
> fix: 修复wayland模式下，无法滚动截图

- .tx/deepin.conf
- debian/changelog
Description: update version 
Log: changelog
> feat: version info

- src/main_window.cpp
Description: 保存到剪贴板
Log: 延时信号链接方式修改
> fix: Wayland

- src/main.cpp
- src/main_window.cpp
- src/utils.cpp
- src/utils.h
Description: 更换保存到剪切板的延时方式、添加一些关键日志
Log: 更换保存到剪切板的延时方式、添加一些关键日志
Bug: https://pms.uniontech.com/bug-view-170721.html
> fix: 更换保存到剪切板的延时方式、添加一些关键日志

- src/main_window.cpp
Description: 截图保存到剪贴板延迟修改
Log: 修改延迟的实现方法，调用Linux的系统时间
> fix: Wayland 截图

- debian/changelog
Description: update version
Log: update changelog
> feat: changelog

- src/main_window.cpp
Description: 保存到剪贴板延迟操作
Log: 延迟操作卡死问题解决
> feat: Wayland 截图

- src/main.cpp
Description: 新增x264编码器是否存在的判断
Log: 新增x264编码器是否存在的判断
Bug: https://pms.uniontech.com/bug-view-158335.html
> fix: 新增x264编码器是否存在的判断

- src/main.cpp
- src/utils/configsettings.cpp
Description: 调整关键日志位置
Log: 调整关键日志位置
> chore: 调整关键日志位置

- src/waylandrecord/waylandintegration.cpp
Description: 新增qingyun的判断
Log: 新增qingyun的判断
> chore: 新增qingyun的判断

- patches/fix-linglong.patch
Description: patches合并有误
Log: patches合并有误
> chore: patches合并有误

- src/main.cpp
Description: 调整代码逻辑，添加关键日志
Log: 调整代码逻辑，添加关键日志
> chore: 调整代码逻辑，添加关键日志

- src/main.cpp
Description: x11和wayland都需要存在h264编码器的情况下，才会走ffmpeg流程，x11还需要判断ffmpeg是否存在
Log: 调整ffmpeg判断条件
> fix: 调整ffmpeg判断条件

- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
Description: 适配wayland接口，防止buffer未被释放导致内存泄漏
Log: 适配wayland接口，防止buffer未被释放导致内存泄漏
> fix: 适配wayland接口，防止buffer未被释放导致内存泄漏

- debian/changelog
Description: 添加changelog
Log: 添加changelog
> chore: 添加changelog

- debian/changelog
Description: 更新changelog
Log: 更新changelog
> chore: 更新changelog

- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
Description: 增加判空，防止返回的图标不存在
Log: 增加判空，防止返回的图标不存在
Bug: https://pms.uniontech.com/bug-view-183675.html
> fix: 增加判空，防止返回的图标不存在

- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
Description: 增加判空，防止返回的图标不存在
Log: 增加判空，防止返回的图标不存在，增加关键日志
Bug: https://pms.uniontech.com/bug-view-183675.html
> fix: 增加判空，防止返回的图标不存在,增加关键日志

- linglong.yaml
Description: 更新依赖的dde-dock版本
Log: 更新依赖的dde-dock版本
> fix: 更新依赖的dde-dock版本

- patches/fix-linglong.patch
Description: v23插件需要重新安装下翻译
Log: v23插件需要重新安装下翻译
> fix: v23插件需要重新安装下翻译

- patches/fix-linglong.patch
Description: 还原代码，去除插件翻译的安装
Log: 还原代码，去除插件翻译的安装
> chore: 还原代码，去除插件翻译的安装

- src/main_window.cpp
Description: 添加规避方案，防止图片数据无法保存到剪切板
Log: 添加规避方案，防止图片数据无法保存到剪切板
> chore: 添加规避方案，防止图片数据无法保存到剪切板

- src/main_window.cpp
- src/widgets/subtoolwidget.cpp
- src/widgets/subtoolwidget.h
Description: 截图自定义保存路径交互简化功能
Log: 截图自定义保存路径交互简化功能
Task: https://pms.uniontech.com/task-view-241885.html
> feat: 截图自定义保存路径交互简化功能

- src/main_window.cpp
Description: 修复录屏时提示段错误，导致无法录屏
Log: 修复录屏时提示段错误，导致无法录屏
Bug: https://pms.uniontech.com/bug-view-185721.html
> fix: 修复录屏时提示段错误，导致无法录屏

- src/main_window.cpp
- src/utils/configsettings.cpp
- src/widgets/subtoolwidget.cpp
- src/widgets/subtoolwidget.h
Description: v23截图和滚动截图自定义保存路径交互简化功能
Log: v23截图和滚动截图自定义保存路径交互简化功能
Task: https://pms.uniontech.com/task-view-241885.html
> feat: v23截图和滚动截图自定义保存路径交互简化功能

- src/utils.cpp
Description: 军用版适配录屏计时插件
Log: 军用版适配录屏计时插件
> fix: 军用版适配录屏计时插件

- src/main_window.cpp
Description: 通过setImageData的方式写入的图片数据格式较多，减少传入的格式，避免wayland协议写数据过慢
Log: wayland下截图只传递png格式的image到剪切板
> fix: wayland下截图只传递png格式的image到剪切板

- src/main_window.cpp
- src/utils.cpp
Description: 合并提交到当前分支
Log: 合并提交到当前分支
> chore: 合并提交到当前分支

- debian/changelog
Description: 更新changelog(5.11.22)
Log: 更新changelog(5.11.22)
> chore: 更新changelog(5.11.22)

- src/src.pro
- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
Description: 1054上remoteaccess协议新增了接口，该接口未同步到低版本，因此做了相关隔离
Log: 兼容性开发
> feat: 兼容性开发

- src/pin_screenshots/mainwindow.cpp
- src/pin_screenshots/pin_screenshots.pro
- src/pin_screenshots/settings.cpp
- src/pin_screenshots/settings.h
- src/pin_screenshots/ui/subtoolwidget.cpp
- src/pin_screenshots/ui/subtoolwidget.h
- src/utils/configsettings.cpp
Description: v20贴图自定义保存位置优化；更新了截图配置文件位置
Log: v20贴图自定义保存位置优化
Task: https://pms.uniontech.com/task-view-241885.html
> feat: v20贴图自定义保存位置优化

- src/pin_screenshots/mainwindow.cpp
- src/pin_screenshots/settings.cpp
- src/pin_screenshots/settings.h
- src/pin_screenshots/ui/subtoolwidget.cpp
- src/pin_screenshots/ui/subtoolwidget.h
Description: v23贴图自定义保存位置优化；更新了截图配置文件位置
Log: v23贴图自定义保存位置优化
Task: https://pms.uniontech.com/task-view-241885.html
> feat: v23贴图自定义保存位置优化

- src/pin_screenshots/mainwindow.cpp
Description: 贴图保存指定位置记忆上次打开文管的位置
Log: 贴图保存指定位置记忆上次打开文管的位置
> chore: 贴图保存指定位置记忆上次打开文管的位置

- src/main_window.cpp
- src/pin_screenshots/mainwindow.cpp
- src/pin_screenshots/ui/subtoolwidget.cpp
- src/widgets/subtoolwidget.cpp
Description: 优化保存到无权限或已删除的目录的逻辑
Log: 优化保存到无权限或已删除的目录的逻辑
> fix: 优化保存到无权限或已删除的目录的逻辑

- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/dde-dock-plugins/shotstart/iconwidget.h
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
Description: 修复录屏时，录制时间在控制中心插件区域中显示
Log: 修复录屏时，录制时间在控制中心插件区域中显示
Bug: https://pms.uniontech.com/bug-view-185807.html
> fix: 修复录屏时，录制时间在控制中心插件区域中显示

- debian/changelog
Description: 更新changlog(5.12.1)
Log: 更新changlog(5.12.1)
> chore: 更新changlog(5.12.1)

- src/main_window.cpp
- src/record_process.cpp
- src/waylandrecord/waylandintegration.cpp
- src/widgets/subtoolwidget.cpp
Description: 添加关键流程日志
Log: 添加关键流程日志
> chore: 添加关键流程日志

- src/camera/majorimageprocessingthread.cpp
- src/main_window.cpp
- src/record_process.cpp
- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
- src/widgets/subtoolwidget.cpp
- src/widgets/zoomIndicator.cpp
Description:  同步release/eagle的修改到当前分支
Log:  同步release/eagle的修改到当前分支
> chore: 同步release/eagle的修改到当前分支

- src/src.pro
- src/waylandrecord/waylandintegration.cpp
Description: 兼容性开发合入
Log: 兼容性开发合入
> feat: 兼容性开发合入

- src/main_window.cpp
- src/widgets/zoomIndicator.cpp
- src/widgets/zoomIndicator.h
Description: 由于opengl绘制放大镜过慢
Log: 修复双屏模式录屏选择有时延
Bug: https://pms.uniontech.com/bug-view-192049.html
> fix: 修复双屏模式录屏选择有时延

- debian/changelog
Description: 更新changelog（5.11.23）
Log: 更新changelog（5.11.23）
> chore: 更新changelog（5.11.23）

- src/record_process.cpp
Description: 修复部分机型录屏结束后，播放视频有7秒没有声音
Log: 修复部分机型录屏结束后，播放视频有7秒没有声音
> fix: 修复部分机型录屏结束后，播放视频有7秒没有声音

- src/waylandrecord/waylandintegration.cpp
Description: 在1053上屏蔽窗管强依赖部分
Log: 在1053上屏蔽窗管强依赖部分
> fix: 在1053上屏蔽窗管强依赖部分

- debian/changelog
- src/main_window.cpp
- src/src.pro
- src/utils/scrollScreenshot.cpp
Description: 更新changlog(5.12.2)及一些注释
Log: 更新changlog(5.12.2)
> chore: 更新changlog(5.12.2)

- src/waylandrecord/waylandintegration.cpp
Description: 增加hw新机型判断
Log: 增加hw新机型判断
> chore: 增加hw新机型判断

- src/pin_screenshots/ui/subtoolwidget.cpp
Description: 修复贴图无法打开的问题
Log: 修复贴图无法打开的问题
Bug: https://pms.uniontech.com/bug-view-199019.html
> fix: 修复贴图无法打开的问题

- debian/changelog
- debian/control
- debian/deepin-screen-recorder-plugin.install
- debian/deepin-screen-recorder.install
Graded control
Log: Graded control
> fix: Graded control

- src/src.pro
Description: 由于同窗管有强依赖，需要回落到1054
Log: 105x打开兼容性宏开关
> chore: 105x打开兼容性宏开关

- debian/changelog
Description: 更新changelog（5.11.24）
Log: 更新changelog（5.11.24）
> chore: 更新changelog（5.11.24）

- debian/changelog
- debian/control
Graded control config Replaces and Conflicts
Log: Graded control config Replaces and Conflicts
> fix: Graded control config Replaces and Conflicts

- src/main_window.cpp
- src/utils/configsettings.h
- src/widgets/subtoolwidget.cpp
Description: 没有通过配置文件初始化鼠标点击的选项
Log: 修复勾选"显示鼠标点击"，录屏时却未显示
Bug: https://pms.uniontech.com/bug-view-199657.html
> fix: 修复勾选"显示鼠标点击"，录屏时却未显示

- debian/control
> fix: unmet runtime depends

- debian/changelog
Description: 更新changelog(5.12.6)
Log: 更新changelog(5.12.6)
> chore: 更新changelog(5.12.6)

- src/main_window.cpp
- src/main_window.h
- src/record_process.cpp
Description: 由于开始录屏之前，就会将需要录制的屏幕大小给进去，录制过程中，不允许修改分辨率
Log: 录屏时不允许改变屏幕分辨率
> fix: 录屏时不允许改变屏幕分辨率

- src/waylandrecord/waylandintegration.cpp
Description: 新增hw机型判断
Log: 新增hw机型判断
> chore: 新增hw机型判断

- assets/org.deepin.screen-recorder.record.json
- debian/deepin-screen-recorder.install
- src/main_window.cpp
- src/main_window.h
- src/src.pro
- src/utils.cpp
- src/utils.h
- src/waylandrecord/waylandintegration.cpp
Description: hw机型判断适配dconfig
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html
> feat: hw机型判断适配dconfig

- debian/changelog
Description: 更新changelog（5.12.7）
Log: 更新changelog（5.12.7）
> chore: 更新changelog（5.12.7）

- debian/control
- debian/deepin-screen-recorder-plugin.install
- debian/deepin-screen-recorder.install
> fix: 插件功能回退

- debian/changelog
Description: 更新changlelog（5.12.8）
Log: 更新changlelog（5.12.8）
> chore: 更新changlelog（5.12.8）

- src/dbusservice/dbusscreenshotservice.cpp
- src/dbusservice/dbusscreenshotservice.h
- src/main.cpp
- src/main_window.cpp
- src/main_window.h
- src/record_process.cpp
- src/screenshot.cpp
- src/screenshot.h
Description: 需求转bug，命令行和dbus接口新增直接启动全屏录制功能
Log: 需求转bug，命令行和dbus接口新增直接启动全屏录制功能
Bug: https://pms.uniontech.com/bug-view-213709.html
> fix: 需求转bug，命令行和dbus接口新增直接启动全屏录制功能

- src/main.cpp
Description: 命令行帮助不显示快捷录制全屏
Log: 命令行帮助不显示快捷录制全屏
> chore: 命令行帮助不显示快捷录制全屏

- debian/changelog
Description: 更新changelog（5.12.9）
Log: 更新changelog（5.12.9）
> chore: 更新changelog（5.12.9）

- src/waylandrecord/waylandintegration.cpp
Description: 1070 amd平台wayland下录屏存在问题，需要适配不存在openGl ES的情况
Log: 适配1070窗管关于openGl ES的支持
> chore: 适配1070窗管关于openGl ES的支持

- src/waylandrecord/waylandintegration.cpp
Description: 华为机型不初始化egl
Log: 华为机型不初始化egl
> fix: 华为机型不初始化egl

- debian/changelog
Description: 更新changelog（5.12.10）
Log: 更新changelog（5.12.10）
> chore: 更新changelog（5.12.10）

- debian/changelog
Description: 更新changelog（5.12.11）
Log: 更新changelog（5.12.11）
> chore: 更新changelog（5.12.11）

- src/dde-dock-plugins/shotstart/shotstartplugin.h
Description: Convert to hexadecimal
Log: Convert to hexadecimal
> fix: Convert to hexadecimal

- patches/fix-linglong.patch
- src/main.cpp
- src/main_window.cpp
- src/pin_screenshots/mainwindow.cpp
> fix: don't hardcode /usr/bin path

- screen_shot_recorder.pro
- src/dde-dock-plugins/recordtime/recordtime.pro
- src/dde-dock-plugins/shotstart/shotstart.pro
- src/pin_screenshots/pin_screenshots.pro
- src/src.pro
> feat: use PREFIX to set install path in qmake

- src/record_process.cpp
Description: 修修复录屏结束后，播放视频有7秒没有声音
Log: 修复录屏结束后，播放视频有7秒没有声音
> chore: 修复录屏结束后，播放视频有7秒没有声音

- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstart/shotstartplugin.h
Description: fix some bug of quick panel
Log: fix some bug of quick panel
> fix: fix some bug of quick panel

- debian/changelog
Description: update changelog(5.12.12).
Log: update changelog(5.12.12).
> chore: update changelog(5.12.12).

- debian/changelog
Description: update changelog.(5.12.13)
Log: update changelog.(5.12.13)
> chore: update changelog.(5.12.13)

- src/main.cpp
Description: 合并关于bug204839的修复到当前分支
Log: 合并关于bug204839的修复到当前分支
> fix: 合并关于bug204839的修复到当前分支

- translations/deepin-screen-recorder_ar.ts
- translations/deepin-screen-recorder_bo.ts
- translations/deepin-screen-recorder_br.ts
- translations/deepin-screen-recorder_ca.ts
- translations/deepin-screen-recorder_cs.ts
- translations/deepin-screen-recorder_da.ts
- translations/deepin-screen-recorder_de.ts
- translations/deepin-screen-recorder_en_US.ts
- translations/deepin-screen-recorder_es.ts
- translations/deepin-screen-recorder_fi.ts
- translations/deepin-screen-recorder_fr.ts
- translations/deepin-screen-recorder_gl_ES.ts
- translations/deepin-screen-recorder_hu.ts
- translations/deepin-screen-recorder_it.ts
- translations/deepin-screen-recorder_ko.ts
- translations/deepin-screen-recorder_ms.ts
- translations/deepin-screen-recorder_nl.ts
- translations/deepin-screen-recorder_pl.ts
- translations/deepin-screen-recorder_pt.ts
- translations/deepin-screen-recorder_pt_BR.ts
- translations/deepin-screen-recorder_ru.ts
- translations/deepin-screen-recorder_sq.ts
- translations/deepin-screen-recorder_sr.ts
- translations/deepin-screen-recorder_tr.ts
- translations/deepin-screen-recorder_ug.ts
- translations/deepin-screen-recorder_uk.ts
- translations/deepin-screen-recorder_zh_CN.ts
- translations/deepin-screen-recorder_zh_HK.ts
- translations/deepin-screen-recorder_zh_TW.ts
Description: 新增“保存时更新路径”的藏语翻译
Log: 新增“保存时更新路径”的藏语翻译
> fix: 新增“保存时更新路径”的藏语翻译

- src/waylandrecord/waylandintegration.cpp
Description: 新增机型判断
Log: 新增机型判断
> chore: 新增机型判断

- debian/changelog
Description: update changelog（5.12.14）
Log: update changelog（5.12.14）
> chore: update changelog（5.12.14）

- src/main_window.cpp
Description: 此方案是规避方案，在将数据传递到剪切板时，延时3s钟，确保数据完全传递到剪切板之后，截图录屏应用才退出
Log: 修复双屏跨屏全屏截图，无法保存到剪切板
Bug: https://pms.uniontech.com/bug-view-237073.html
> fix: 修复双屏跨屏全屏截图，无法保存到剪切板

- debian/changelog
Description: update changelog(5.12.15).
Log: update changelog(5.12.15).
> chore: update changelog(5.12.15).

- debian/changelog
Description: update changelog(5.12.16).
Log: update changelog(5.12.16).
> chore: update changelog(5.12.16).

- debian/changelog
Description: update changelog(5.12.17)
Log: update changelog(5.12.17)
> chore: update changelog(5.12.17)

- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
Description: 修复双屏录制的视频会出现黑屏现象
Log: 修复双屏录制的视频会出现黑屏现象
Bug: https://pms.uniontech.com/bug-view-242023.html
https://pms.uniontech.com/bug-view-233493.html
> fix: 修复双屏录制的视频会出现黑屏现象

- src/main_window.cpp
Description: 修复截图录屏概率性因为获取所有窗口信息导致自动退出
Log: 修复截图录屏概率性因为获取所有窗口信息导致自动退出
> fix: 修复截图录屏概率性因为获取所有窗口信息导致自动退出

- src/pin_screenshots/main.cpp
Description: 修复调整显示器缩放比之后，icon缩放失真的问题
Log: 修复调整显示器缩放比之后，icon缩放失真的问题
Bug: https://pms.uniontech.com/bug-view-243881.html###
> fix: 修复调整显示器缩放比之后，icon缩放失真的问题

- 3rdparty/libcam/libcam_encoder/encoder.c
- 3rdparty/libcam/libcam_v4l2core/jpeg_decoder.c
- 3rdparty/libcam/libcam_v4l2core/uvc_h264.c
- 3rdparty/libcam/load_libs.c
Description: 修复截图录屏工具使用闪退
Log: 修复截图录屏工具使用闪退
Bug: https://pms.uniontech.com/bug-view-246231.html
> fix: 修复截图录屏工具使用闪退

- debian/changelog
update the baseline version to 6.0.3
Log: update the baseline version to 6.0.3
Bug: no
> feat: update to 6.0.3

- src/dde-dock-plugins/shotstartrecord/res.qrc
- src/dde-dock-plugins/shotstartrecord/res/shot-start-record-plugin-dark.svg
- src/dde-dock-plugins/shotstartrecord/shotstartrecord.pro
调整托盘图标文件路径，影响在控制中心的显示效果
Log: 修复界面显示问题
> fix: Adjust dde-dock tray icon path

- src/dde-dock-plugins/recordtime/timewidget.cpp
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
功能代码被日志判断跳过，将其移出日志打印代码。
Log: 修复部分功能问题
> fix: Function code is skipped by log judgment

- debian/changelog
update the baseline version to 6.0.4
Log: update the baseline version to 6.0.4
Bug: no
> feat: update to 6.0.4

- debian/changelog
- src/dde-dock-plugins/recordtime/timewidget.cpp
fix taskbar time display error when screencap
Log: Taskbar time display error when screencap
Bug: https://pms.uniontech.com/bug-view-251951.html
> fix: taskbar time display error when screencap

- src/utils/borderprocessinterface.cpp
- src/utils/borderprocessinterface.h
调整截图投影效果,现有DTK接口不能完全满足需求,
参考DTK实现.
Log: 调整截图投影效果
Task: https://pms.uniontech.com/story-view-33231.html
> feat: Update screenshot dropshadow effect

- debian/control
Remove ffmpeg dependency
Log: Remove ffmpeg dependency
> fix: Remove ffmpeg dependency

- src/pin_screenshots/mainwindow.cpp
截屏贴图-触发贴图后滑动鼠标滚轮缩放，窗口不能超出屏幕
Log: 截屏贴图-触发贴图后滑动鼠标滚轮缩放，窗口不能超出屏幕
Bug: https://pms.uniontech.com/bug-view-249185.html
> fix: 贴图不能移动出屏幕

- debian/control
This reverts commit 2dd073d71b7ef6f754302c86297a7d7ac7b75ad3.
> Revert "fix: Remove ffmpeg dependency (#486)"

- src/record_process.cpp
the temporal performance of recording gif
Log: the temporal performance of recording gif
Bug: https://pms.uniontech.com/bug-view-264145.html
> fix: the temporal performance of recording gif

- src/dde-dock-plugins/recordtime/timewidget.cpp
- src/dde-dock-plugins/recordtime/timewidget.h
* 使用 layout 和 widget 替代手动绘制
* 大小自适应
* 适配 dde-tray-loader
Issues: linuxdeepin/developer-center#9820
> fix: 修复 dde-shell 样式

- src/main.cpp
Part of the screenshot is black in screen expansion and zoom mode.
Log: fix the black part in screen recorder
Bug: https://pms.uniontech.com/bug-view-205567.html
> fix: the black part in screen recorder

- src/main_window.cpp
fix the toolbar incorrect coordinate position display
Log: fix the toolbar incorrect coordinate position display
Bug: https://pms.uniontech.com/bug-view-261623.html
> fix: the toolbar incorrect position display

- src/main_window.cpp
Reverts linuxdeepin/deepin-screen-recorder#510
> Revert "fix: Adjust the time sequence of the screenshot completion prompt"

- src/dde-dock-plugins/recordtime/recordtimeplugin.h
设置 PluginSizePolicy 为 Custom
Issues: linuxdeepin/developer-center#10130
> chore: 录屏时间插件移动到任务栏固定区域

- src/dde-dock-plugins/recordtime/timewidget.cpp
Log: fix the recorder taskbar incorrect background-color
Bug: https://pms.uniontech.com/bug-view-267669.html
> fix: the recorder taskbar incorrect background-color

- src/dde-dock-plugins/recordtime/recordtimeplugin.h
强制显示在任务栏
Issues: linuxdeepin/developer-center#9619
> chore: add ForceDock flag

- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
fix the blur screen in other resolution ratio
Log: fix the blur screen in other resolution ratio
Bug: https://pms.uniontech.com/bug-view-266061.html
> fix: the blur screen in other resolution ratio

- src/dde-dock-plugins/recordtime/recordtimeplugin.h
Type_Tool 会被识别为 fixed
Issues: linuxdeepin/developer-center#10399
> chore: change the plugin type

- src/record_process.cpp
Log: the quick panel not show the recorde time
Bug: https://pms.uniontech.com/bug-view-268597.html
> fix: the quick panel not show the recorde time

- debian/changelog
changelog 6.0.9
Log: changelog 6.0.9
> fix: changelog 6.0.9

- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
fix after click the quick panel item to hide the panel
Log: fix after click the quick panel item to hide the panel
Bug: https://pms.uniontech.com/bug-view-272307.html
> fix: after click the quick panel item to hide the panel

- src/utils.cpp
- src/utils/audioutils.cpp
- src/waylandrecord/avinputstream.cpp
- src/waylandrecord/waylandintegration.cpp
Optimize command line acquisition parameters
Log: Optimize command line acquisition parameters
Task: https://pms.uniontech.com/task-view-362613.html
> fix: Optimize command line acquisition parameters

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- src/dde-dock-plugins/recordtime/timewidget.cpp
- src/dde-dock-plugins/recordtime/timewidget.h
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
- src/main.cpp
- src/pin_screenshots/main.cpp
- src/src.pro
1. sync release/eagle branch code.
2. adapt treeland and new system edition 
Adapt Treeland, disable wayland settings in Treeland enviroment.
1. The new version of Treeland is temporarily unstable;
2. The V23 version of KWayland does not incorporate the modifications
of the professional version, and some interfaces are not provided;
4. The latest version is community-based.
> feat: sync code and adapt new system edition 

- src/src.pro
As title.
Log: Update comment.
> style: update comment

- src/main_window.cpp
fix the config button status
Log: fix the config button status
Bug: https://pms.uniontech.com/bug-view-270437.html
> fix: the config button status

- src/main_window.cpp
fix the pinscreenshot tips window show not correct.
Log: fix the pinscreenshot tips
Bug: https://pms.uniontech.com/bug-view-275657.html
> fix: the pinscreenshot tips

- src/pin_screenshots/ui/subtoolwidget.cpp
fix the pinscreenshot save format error
Log: fix the pinscreenshot save format error
Bug: https://pms.uniontech.com/bug-view-276833.html
> fix: the pinscreenshot save format error

- src/screenshot.cpp
fix the offset problem when dual-screen non-alignment
Log: fix the offset problem when dual-screen non-alignment
Bug: https://pms.uniontech.com/bug-view-275805.html
> fix: the offset problem when dual-screen non-alignment

- src/main.cpp
fix the dual operation of shotcut
Log: fix the dual operation of shotcut
Bug: https://pms.uniontech.com/bug-view-280201.html
> fix: the dual operation of shotcut

- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
fix the shortcut panel after click the screenshot, the screenshot has the shadow of the shortcut panel
Log: fix the shortcut panel shadow
Bug: https://pms.uniontech.com/bug-view-280671.html
> fix: the shortcut panel shadow

- src/main_window.cpp
- src/main_window.h
fix dormant wake up screen jam during screen recording
Log: fix dormant wake up screen jam during screen recording
Bug: https://pms.uniontech.com/bug-view-280187.html
> fix: the wake up of screen jam

- src/main_window.cpp
fix dormant wake up screen jam during screen recording
Log: fix dormant wake up screen jam during screen recording in sw military
Bug: https://pms.uniontech.com/bug-view-280187.html
> fix: the wake up of screen jam only in sw military

- debian/changelog
changelog 6.0.10
Log: changelog 6.0.10
> fix: changelog 6.0.10

- src/main_window.cpp
fit the screen window layer in 1070, 1060 and 1050
Log: fit the screen window layer in 1070, 1060 and 1050
Bug: https://pms.uniontech.com/bug-view-275661.html
> fix: fit the screen window layer in 1070, 1060 and 1050

- src/main.cpp
- src/src.pro
fix the menu bar not scale to in the high DPI
Log: fix the menu bar not scale to in the high DPI
Bug: https://pms.uniontech.com/bug-view-288187.html
> fix: the menu bar not scale to in the high DPI

- src/utils/screengrabber.cpp
change the get image from wayland for serial times
Log: change the get image from wayland for serial times
Bug: https://pms.uniontech.com/bug-view-289077.html
> fix: change the get image from wayland for serial times

- src/record_process.cpp
Fixed the issue that screen recording fails under ARM
Bug: https://pms.uniontech.com/bug-view-283491.html
Log: Fixed the issue that screen recording fails under ARM
> fix: Fixed the issue that screen recording fails under ARM

- src/utils/screengrabber.cpp
> fix: 修改为1s

- src/src.pro
- src/utils/screengrabber.cpp
- src/utils/screengrabber.h
use ximage to get image when wayland-dbus not work
Log: use ximage to get image when wayland-dbus not work
> feat: use ximage to get image when wayland-dbus not work

- debian/control
> fix: change control

- debian/control
> fix: change control error

- src/main_window.cpp
> fix: handle coredump

- debian/changelog
- src/main_window.cpp
> fix: fix error

- debian/changelog
- src/main_window.cpp
> fix: startup optimization

- screen_shot_recorder.pro
- src/main_window.cpp
- src/widgets/subtoolwidget.cpp
> fix: Addressing translation issues

- src/record_process.cpp
Fixed the issue that screen recording fails under ARM
Bug: https://pms.uniontech.com/bug-view-283491.html
Log: Fixed the issue that screen recording fails under ARM
> fix: Fixed the issue that screen recording fails under ARM (#569)

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- src/dde-dock-plugins/shotstart/iconwidget.h
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
As title.
Log: Fix dock plugin not loaded.
Bug: https://pms.uniontech.com/bug-view-289717.html
> fix: dock plugin not loaded

- debian/changelog
- linglong.yaml
Bump version to 6.5.2
Log: Bump version to 6.5.2
> chore: Bump version to 6.5.2

- src/main_window.cpp
- src/main_window.h
adjust the init wayland-flags position
Log: adjust the init wayland-flags position
Bug: https://pms.uniontech.com/bug-view-289069.html
> fix: adjust the init wayland-flags position

- src/utils/screengrabber.cpp
add the reply print info of kwin screen-shot interface
Log: add the reply print info of kwin screen-shot interface
> fix: add the reply print info of kwin screen-shot interface

- src/main_window.cpp
> fix: Unable to select desktop save

- debian/changelog
- linglong.yaml
Bump version to 6.5.3
Log: Bump version to 6.5.3
> chore: Bump version to 6.5.3

- screen_shot_recorder.pro
- src/camera/devnummonitor.cpp
- src/camera_process.h
- src/event_monitor.cpp
- src/main.cpp
- src/main_window.cpp
- src/pin_screenshots/main.cpp
- src/pin_screenshots/ui/menucontroller.cpp
- src/pin_screenshots/ui/menucontroller.h
- src/pin_screenshots/ui/toolbutton.h
- src/record_process.cpp
- src/utils.cpp
- src/utils.h
- src/utils/pixmergethread.cpp
- src/utils/scrollScreenshot.cpp
- src/widgets/camerawidget.h
- src/widgets/sidebar.cpp
- src/widgets/sidebar.h
- src/widgets/toolbar.cpp
- src/widgets/toolbar.h
- src/widgets/tooltips.cpp
- src/widgets/tooltips.h
- src/widgets/zoomIndicator.cpp
Unified modification of predefined macros
> fix: Unified modification of predefined macros

- screen_shot_recorder.pro
> fix: Translation file not found

- debian/changelog
- linglong.yaml
Bump version to 6.5.4
Log: Bump version to 6.5.4
> chore: bump version to 6.5.4

- debian/changelog
- linglong.yaml
Bump version to 6.5.5
Log: Bump version to 6.5.5
> chore: Bump version to 6.5.5

- debian/changelog
- linglong.yaml
Bump version to 6.5.6
Log: Bump version to 6.5.6
> chore: Bump version to 6.5.6

- src/main.cpp
> fix : delete error log

- debian/changelog
- linglong.yaml
Bump version to 6.5.7
Log: Bump version to 6.5.7
> chore: Bump version to 6.5.7

- src/configs/dbus/NotificationsAdaptor.cpp
- src/configs/dbus/NotificationsAdaptor.h
- src/configs/dbus/ScreenshotAdaptor.cpp
- src/configs/dbus/ScreenshotAdaptor.h
- src/configs/dbus/SoundEffectAdaptor.cpp
- src/configs/dbus/SoundEffectAdaptor.h
- src/configs/dbus/ZoneAdaptor.cpp
- src/configs/dbus/ZoneAdaptor.h
- src/configs/json/org_deepin_screen-recorder_record.hpp
add DBus adaptors for system services
Log: add DBus adaptors for system services
> chore: add DBus adaptors for system services

- src/waylandrecord/waylandintegration.cpp
fix the dual-screen get info may incorrect
Log: the dual-screen get info may incorrect
Bug: https://pms.uniontech.com/bug-view-298757.html
> fix: the dual-screen get info may incorrect

- src/dde-dock-plugins/recordtime/timewidget.cpp
Remove unnecessary margins
Log: Fix record plugin press and hover issue.
Bug: https://pms.uniontech.com/bug-view-301071.html
> fix: Unnecessary margins

- src/waylandrecord/waylandintegration.cpp
fix the dual-screen when only one screen disable
Log: the dual-screen when only one screen disable
Bug: https://pms.uniontech.com/bug-view-298757.html
> fix: the dual-screen when only one screen disable

- src/record_process.cpp
- src/utils/audioutils.cpp
fix the system audio record not work,
due to get the channel error
Log: the dual-screen when only one screen disable
Bug: https://pms.uniontech.com/bug-view-302735.html
> fix: the system audio record not work

- src/record_process.cpp
- src/utils/audioutils.cpp
Fix the audio failure issue in the recording system
Bug: https://pms.uniontech.com/bug-view-297775.html
Log: Fix the audio failure issue in the recording system
> fix: Fix the audio failure issue in the recording system

- src/pin_screenshots/mainwindow.cpp
- src/pin_screenshots/ui/toolbarwidget.cpp
- Active tool bar when show();
- Change window flag to enable roundded corner.
Log: fix pin-screenshots missing rounded corner and focus.
Bug: https://pms.uniontech.com/bug-view-305423.html
> fix: pin-screenshots missing rounded corner and focus

- src/utils/pixmergethread.cpp
Can not copy a empty image.
Log: fix a crash issue.
Bug: https://pms.uniontech.com/bug-view-306355.html
> fix: crash on scroll image

- src/waylandrecord/avoutputstream.cpp
- src/waylandrecord/avoutputstream.h
- src/waylandrecord/recordadmin.cpp
- src/waylandrecord/waylandintegration.cpp
- src/waylandrecord/waylandintegration_p.h
increase encode queue to prove lose video frame.
we also use new image convert to increase the encode speed
Log: use new image format convert to improve fps.
Bug: https://pms.uniontech.com/bug-view-275875.html
> feat: use new image format convert to improve fps.

- src/src.pro
- src/utils.cpp
- src/utils.h
- src/utils/audioutils.cpp
- src/utils/audioutils.h
- src/utils/proxyaudioport.cpp
- src/utils/proxyaudioport.h
- src/utils/voicevolumewatcher.cpp
- src/utils/voicevolumewatcher.h
DFrameworkDBus based on Qt5,
Disable it on Qt6.
Log: fix a compability issue.
> fix: disable v20 interface on Qt6.

- src/main_window.cpp
- src/record_process.cpp
fix the repair selection box is slow to respond to quick drag
Log: fix the repair selection box is slow to respond to quick drag
Bug: https://pms.uniontech.com/bug-view-307899.html
> fix: the repair selection box is slow to respond to quick drag

- debian/changelog
Bump version to 6.5.12
Log: Bump version to 6.5.12
> chore: Bump version to 6.5.12

- debian/changelog
Bump version to 6.5.13
Log: Bump version to 6.5.13
> chore: Bump version to 6.5.13

- debian/changelog
Bump version to 6.5.14
Log: Bump version to 6.5.14
> chore: Bump version to 6.5.14

- src/dde-dock-plugins/shotstartrecord/quickpanelwidget.cpp
Change margins from 8 to 0 for better UI consistency
Log: Adjust quick panel margins
Bug: https://pms.uniontech.com/bug-view-271223.html
> fix: Set quick panel margins to 0

- debian/changelog
Bump version to 6.5.15
Log: Bump version to 6.5.15
> chore: Bump version to 6.5.15

- debian/changelog
Bump version to 6.5.16
Log: Bump version to 6.5.16
> chore: Bump version to 6.5.16

- debian/changelog
- Update version to 6.5.17
Log: Bump version to 6.5.17
> chore: Bump version to 6.5.17

- debian/changelog
- Update version to 6.5.18.
log: Update version to 6.5.18.
> chore: Update version to 6.5.18

- src/dde-dock-plugins/recordtime/recordtimeplugin.cpp
- src/dde-dock-plugins/shotstart/shotstart.pro
- src/dde-dock-plugins/shotstart/shotstartplugin.cpp
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
The log name is not init that cause plugin can not be loaded.
Log: Fix the plugins can not be loaded issue.
Bug: https://pms.uniontech.com/bug-view-319363.html
> fix: Fix the plugins can not be loaded issue

- .gitignore
- debian/changelog
- src/dbus/com_deepin_daemon_audio.h
- src/dbus/com_deepin_daemon_audio_sink.h
- src/dbus/com_deepin_daemon_audio_source.h
- src/dbus_name.cpp
- src/dbus_name.h
- src/dbusinterface/dbuscontrolcenter.cpp
- src/dbusinterface/dbuscontrolcenter.h
- src/dbusinterface/dbussoundeffect.cpp
- src/dbusinterface/dbussoundeffect.h
- src/dbusinterface/dbuszone.cpp
- src/dbusinterface/dbuszone.h
- src/dde-dock-plugins/shotstart/iconwidget.cpp
- src/dde-dock-plugins/shotstart/iconwidget_interface.h
- src/dde-dock-plugins/shotstart/shotstart.pro
- src/dde-dock-plugins/shotstartrecord/recordiconwidget.cpp
- src/dde-dock-plugins/shotstartrecord/recordiconwidget_interface.h
- src/dde-dock-plugins/shotstartrecord/shotstartrecord.pro
- src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
- src/event_monitor.cpp
- src/main_window.cpp
- src/src.pro
- src/utils.cpp
- src/utils/com_deepin_daemon_audio.h
- src/utils/shortcut.cpp
- src/utils/voicevolumewatcher_interface.h
- src/utils_interface.h
- src/waylandrecord/waylandintegration.cpp
- tests/ut_screen_shot_recorder/utils/ut_dbusutils.h
As title.
Log: Adapt to V23 dde dbus interface
> feat: Adapt to V23 dde dbus interface

- .gitignore
- src/src.pro
- Added .cursorindexingignore to .gitignore for improved file management.
- Updated QMAKE_CXXFLAGS in src.pro to include -fPIE for better security and compatibility.
Log: Fix build fail on arm64
> chore: Update .gitignore and enhance compiler flags

- src/src.pro
- Added -g, -Wall, and -fPIE to QMAKE_CFLAGS for better debugging and security practices.
Log: Enhance compiler flags for improved debugging and security.
> chore: Enhance compiler flags for improved debugging and security

- debian/changelog
Update version to 6.5.22.
Log: Update version to 6.5.22
> chore: Update version to 6.5.22

- 3rdparty/libcam/libcam_encoder/encoder.c
> feat: Support ffmepg 7

- debian/changelog
- translations/deepin-screen-recorder_zh_CN.ts
- translations/deepin-screen-recorder_zh_HK.ts
- translations/deepin-screen-recorder_zh_TW.ts
update translation
Log: update translation
> chore: update translation

- debian/changelog
- src/utils/screengrabber.cpp
- src/utils/screengrabber.h
fix: Enhance screenshot functionality for multi-screen setups
- Added device pixel ratio handling to improve screenshot quality across different screen resolutions.
- Improved layout detection for multi-screen environments to handle complex arrangements.
Log: Enhance screenshot functionality for better multi-screen support.
bug: https://pms.uniontech.com/bug-view-322605.html
> fix: Enhance screenshot functionality for multi-screen setups

- src/utils/screengrabber.cpp
add log info for fullscreenshot
Log: add log info for fullscreenshot
Bug: https://pms.uniontech.com/bug-view-328797.html
> fix: add log info for fullscreenshot

- debian/changelog
- update version to 6.6.4
log: update version to 6.6.4
> chore: Update version to 6.6.4

- src/waylandrecord/waylandintegration.cpp
When adjusting the system time, the timestamp will change according to the system time change during the recording process, resulting in the problem of time jumping.
Log: adjust timestamp for video stream.
Bug: https://pms.uniontech.com/bug-view-268369.html
> fix: screen recording timestamp adjustment for video stream.

- debian/changelog
- update version to 6.6.6
log: update version to 6.6.6
>  chore: Update version to 6.6.6
