src/main_window.cpp, src/record_process.cpp, src/record_process.h
开启缩放以后，dtkwm提供了错误的坐标，录屏在计算时也计算错误，导致在非主屏上录像
永远是在主屏位置的信息。
fix dtkwm: https://github.com/linuxdeepin/dtkwm/pull/2
=> fix: multiple screens cannot be recorded after set window scale

src/pin_screenshots/ui/toolbarwidget.cpp, src/pin_screenshots/ui/toolbarwidget.h
fix:  (wayland)修复贴图工具栏可以单独拖动
Description:  由于贴图工具栏的鼠标移动事件未屏蔽
Log:  修复贴图工具栏可以单独拖动
Bug: https://pms.uniontech.com/bug-view-121331.html
=> fix:  (wayland)修复贴图工具栏可以单独拖动

src/gstrecord/gstrecordx.cpp, src/main_window.cpp, src/main_window.h
Description: gstremer中ximagesrc的bug，录制区域的终点有问题
Log: 修复调整捕捉区域后，录制的画面区域不正确
Bug: https://pms.uniontech.com/bug-view-127641.html
https://pms.uniontech.com/bug-view-127963.html
=> fix: (x11)修复调整捕捉区域后，录制的画面区域不正确

src/main_window.cpp, src/main_window.h, src/pin_screenshots/ui/toolbarwidget.cpp, src/pin_screenshots/ui/toolbarwidget.h
Description:  由于贴图工具栏的鼠标移动事件未屏蔽
Log:  修复贴图工具栏可以单独拖动
Bug: https://pms.uniontech.com/bug-view-121331.html
=> fix: (wayland)修复贴图工具栏可以单独拖动

src/widgets/subtoolwidget.cpp
Description: ffmeg录制gif时写入配置，切换到gstreamer时未进行判断
Log: 修复Gstreamer启动录屏后未选择webm格式
Bug: https://pms.uniontech.com/bug-view-128269.html
=> fix: 修复Gstreamer启动录屏后未选择webm格式

src/gstrecord/gstrecordx.cpp
Description: 由于视频的像素格式不对
Log: 修复klv录制花屏
Bug: https://pms.uniontech.com/bug-view-129883.html
=> fix: (Gstreamer)修复klv录制花屏

src/main_window.cpp
Description: 由于wayland上下拉菜单的焦点激活方式与x11有区别，做规避处理
Log: 修复在选项区域上滑动鼠标，移出选项区域后，鼠标变成“+”
Bug: https://pms.uniontech.com/bug-view-132763.html
=> fix: 修复在选项区域上滑动鼠标，移出选项区域后，鼠标变成“+”

src/main_window.cpp
Description: 双击保存按钮，导致保存两次
Log: https://pms.uniontech.com/bug-view-138635.html
=> fix(截图): 截图保存

src/button_feedback.cpp, src/utils.cpp, src/utils.h
Description: 修复双屏1.25缩放比下录屏点击效果位置偏差
Log: 修复双屏1.25缩放比下录屏点击效果位置偏差
Bug: https://pms.uniontech.com/bug-view-141063.html
=> fix: 修复双屏1.25缩放比下录屏点击效果位置偏差

debian/control, src/main.cpp
Description: 由于contral中强依赖于ffmpeg，x11录屏时如果没有ffmpeg应用将会使用gstreamer录屏
Log: 修复卸载ffmpeg时，会同时把截图录屏卸载
Bug: https://pms.uniontech.com/bug-view-141357.html
=> fix: 修复卸载ffmpeg时，会同时把截图录屏卸载

src/record_process.cpp, src/utils/audioutils.cpp, src/waylandrecord/avinputstream.cpp, src/waylandrecord/recordadmin.cpp
Description:  由于klv上出现一个虚拟声卡，该虚拟声卡未适配导致ffmpeg无法获取声卡数据而卡死
Log:  优化录屏时获取真实声卡的方式
Bug: https://pms.uniontech.com/bug-view-140811.html
=> fix:  优化录屏时获取真实声卡的方式

src/dde-dock-plugins/shotstart/shotstartplugin.cpp, src/dde-dock-plugins/shotstart/shotstartplugin.h
Description: 之前位指定截图录屏的默认位置，导致位置可能不确定
Log: 优化截图录屏任务栏插件的默认显示位置
Bug: https://pms.uniontech.com/bug-view-130339.html
=> fix: 优化截图录屏任务栏插件的默认显示位置

tests/ut_dde_dock_plugins/ut_record_time/ut_timewidget.cpp
Description: 由于修改源码后未修改单元测试中对应的比较值
Log: 修复失败的单元测试用例
Bug: https://pms.uniontech.com/bug-view-144065.html
=> fix: 修复失败的单元测试用例

src/main_window.cpp, src/widgets/zoomIndicator.cpp
Description:  由于录屏区域的y坐标出现一个负值导致ffmpeg无法识别正确的录屏位置
Log:  优化录屏时录屏区域的位置判断
Bug: https://pms.uniontech.com/bug-view-143969.html
=> fix:  优化录屏时录屏区域的位置判断

src/main_window.cpp, src/main_window.h
Description: 由于X11底层函数无法正常执行，导致截图录屏卡住，无法正常释放
Log: 添加超时机制，确保全局事件监听线程正常退出
=> fix: 添加超时机制，确保全局事件监听线程正常退出

src/main_window.cpp
Description:  由于在滚动截图模式中锁屏，保存到剪贴板被卡住，导致解锁后截图录屏程序没有退出，因此无法启动滚动截图
Log:  优化剪贴板保存机制，加了一个1s超时机制
Bug: https://pms.uniontech.com/bug-view-146103.html
=> fix: (wayland) 优化剪贴板保存机制，加了一个1s超时机制

src/pin_screenshots/mainwindow.cpp
Description:  由于贴图传递给通知的参数与截图录屏不一致
Log:  修复在通知设置中关闭截图录屏,贴图功能仍然有通知的提示信息
Bug: https://pms.uniontech.com/bug-view-139389.html
=> fix: 修复在通知设置中关闭截图录屏,贴图功能仍然有通知的提示信息

src/main_window.cpp
Description:  由于计算框选位置时没考虑屏幕位置
Log:  修复自动识别窗口时，框选的区域发生偏移
Bug: https://pms.uniontech.com/bug-view-149993.html
=> fix: 修复自动识别窗口时，框选的区域发生偏移

src/widgets/zoomIndicator.cpp, src/widgets/zoomIndicator.h
Description:  由于opengl绘制的widget，执行move函数卡顿
Log:  优化多任务视图界面，选择截图区域卡顿的问题
Bug: https://pms.uniontech.com/bug-view-137639.html
=> fix: 优化多任务视图界面，选择截图区域卡顿的问题

src/main_window.cpp
避免硬编码查找路径，提高可移植性。
另外，对于在文件管理器中显示指定文件的需求，也应当考虑使用 DTK 中提供的 `DFileServices::showFileItem()`。
是解决 https://github.com/linuxdeepin/developer-center/issues/3374 问题的一部分。
=> fix: don't hardcode /usr/bin path

src/dbusservice/dbusscreenshotservice.cpp, src/main_window.cpp, src/screenshot.cpp
Description:  由于截图程序的初始化未完成
Log:  修复“图文识别“快捷键在鼠标移动时按下，功能闪退无法正常启动
Bug: https://pms.uniontech.com/bug-view-155781.html
=> fix: 修复“图文识别“快捷键在鼠标移动时按下，功能闪退无法正常启动

3rdparty/libcam/libcam_v4l2core/v4l2_controls.c, src/main_window.cpp
Description: wayland下截图录屏的窗口层级不在最顶层
Log: 修复录制视频打开摄像头后，影院窗口全屏会遮挡摄像头画面
Bug: https://pms.uniontech.com/bug-view-130443.html
=> fix: 修复录制视频打开摄像头后，影院窗口全屏会遮挡摄像头画面

src/main_window.cpp, src/main_window.h
Description: 修复截取屏幕周边的小范围区域时，工具栏会遮盖截图区域
Log: 修复截取屏幕周边的小范围区域时，工具栏会遮盖截图区域
Bug: https://pms.uniontech.com/bug-view-166887.html
=> fix: 修复截取屏幕周边的小范围区域时，工具栏会遮盖截图区域

tests/ut_dde_dock_plugins/ut_record_time/ut_timewidget.cpp
Description: 修复2022/11/02 单元测试失败用例
Log: 修复2022/11/02 单元测试失败用例
Bug: https://pms.uniontech.com/bug-view-169309.html
=> fix: 修复2022/11/02 单元测试失败用例

src/main_window.cpp, src/main_window.h
Description: 修复外接扩展屏在设置不同分辨率的情况下，使用截图录屏时工具栏无法在屏幕内正常显示的问题
Log: 修复外接扩展屏在设置不同分辨率的情况下，使用截图录屏时工具栏无法在屏幕内正常显示的问题
Bug: https://pms.uniontech.com/bug-view-162523.html
=> fix: 修复外接扩展屏在设置不同分辨率的情况下，使用截图录屏时工具栏无法在屏幕内正常显示的问题

src/main_window.cpp, src/utils/shapesutils.h, src/widgets/shapeswidget.cpp, src/widgets/shapeswidget.h, src/widgets/textedit.cpp, src/widgets/textedit.h
Description: 修复使用截图工具：圆形、箭头等框出重要关键字，保存图片后所画的图形，箭头等形状停留在桌面上2s后消失
Log: 修复使用截图工具：圆形、箭头等框出重要关键字，保存图片后所画的图形，箭头等形状停留在桌面上2s后消失
Bug: https://pms.uniontech.com/bug-view-170101.html
=> fix: 修复使用截图工具：圆形、箭头等框出重要关键字，保存图片后所画的图形，箭头等形状停留在桌面上2s后消失

debian/control, src/widgets/toolbar.cpp
Description: (UI) 修复截图&录屏的完成按钮圆角不对,去除了两个未使用的依赖
Log: (UI) 修复截图&录屏的完成按钮圆角不对
Bug: https://pms.uniontech.com/bug-view-156653.html
=> fix: (UI) 修复截图&录屏的完成按钮圆角不对

src/main_window.cpp
Description: 修复选择文字工具，shift转换中英文，然后使用箭头工具，箭头只能90度转向
Log: 修复选择文字工具，shift转换中英文，然后使用箭头工具，箭头只能90度转向
Bug: https://pms.uniontech.com/bug-view-163479.html
=> fix: 修复选择文字工具，shift转换中英文，然后使用箭头工具，箭头只能90度转向

src/camera/majorimageprocessingthread.cpp, src/camera/majorimageprocessingthread.h, src/widgets/camerawidget.cpp, src/widgets/camerawidget.h
Description: 修复录屏时同时存在显示按键和摄像头时，按键盘会使摄像头闪烁
Log: 修复录屏时同时存在显示按键和摄像头时，按键盘会使摄像头闪烁
Bug: https://pms.uniontech.com/bug-view-172567.html
=> fix: 修复录屏时同时存在显示按键和摄像头时，按键盘会使摄像头闪烁

src/main_window.cpp
Description: 由于华为某些机型概率不能保存到剪切板，还是需要还原延时等待操作
Log: 调整wayland保存到剪切板的逻辑
=> fix: 调整wayland保存到剪切板的逻辑

src/main_window.cpp
Description: 修复在高分屏扩展加缩放下，截图工具栏消失的问题
Log: 修复在高分屏扩展加缩放下，截图工具栏消失的问题
Bug: https://pms.uniontech.com/bug-view-162523.html
=> fix: 修复在高分屏扩展加缩放下，截图工具栏消失的问题

src/dde-dock-plugins/recordtime/timewidget.cpp
Description: 修复分屏在2.0倍显示下，录屏图标在任务栏显示会被遮挡
Log: 修复分屏在2.0倍显示下，录屏图标在任务栏显示会被遮挡
Bug: https://pms.uniontech.com/bug-view-175341.html
=> fix: 修复分屏在2.0倍显示下，录屏图标在任务栏显示会被遮挡

src/record_process.cpp
根据社区论坛的用户反馈,录制的视频无法在苹果手机播放
https://bbs.deepin.org/post/245693
Log: 修复录制的视频无法在苹果手机播放
=> fix: Can not Play Recorded mp4 videos on iPhone

debian/control, debian/source/format, src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/shotstart/iconwidget.cpp, src/dde-dock-plugins/shotstart/iconwidget.h, src/dde-dock-plugins/shotstart/shotstartplugin.cpp
Description: 修复启用截图录屏，高分屏机器上任务栏图标显示异常
Log: 修复启用截图录屏，高分屏机器上任务栏图标显示异常
Bug: https://pms.uniontech.com/bug-view-183665.html
=> fix: 修复启用截图录屏，高分屏机器上任务栏图标显示异常

src/main_window.cpp
Description: wayland下录屏开始之后浏览器中无法获取键盘输入，由于onscreendisplay属性导致。
Log: 屏蔽录屏开始之后的焦点获取
=> fix: 屏蔽录屏开始之后的焦点获取

deepin-screen-recorder.desktop
In 8559f78d85775fca0d7ee38da646f095864377e3 the `OnlyShowIn` entry was added to forbid it from being shown in DeepinTablet. This unfortunately has the side effect that disables the icon from other desktop environments either.
Let's use `NotShowIn` instead to better align with the original goal and fixes the problem.
Fixes https://github.com/orgs/linuxdeepin/discussions/3560
Log: Show application icon in other desktop environments
=> fix: show application icon in other desktop environments

patches/fix-linglong.patch
Description: 修复托盘区域和个性化-桌面版，插件区域下，截图录屏未进行翻译
Log: 修复托盘区域和个性化-桌面版，插件区域下，截图录屏未进行翻译
Bug: https://pms.uniontech.com/bug-view-184057.html
=> fix: 修复托盘区域和个性化-桌面版，插件区域下，截图录屏未进行翻译

src/main_window.cpp
Description: 添加事件循环等待保存到剪切板
Log: 修复截图后数据未保存到剪切板
Bug: https://pms.uniontech.com/bug-view-184637.html
=> fix: 修复截图后数据未保存到剪切板

src/accessibility/acTextDefine.h, src/dde-dock-plugins/shotstart/shotstartplugin.cpp, src/main_window.cpp, src/widgets/subtoolwidget.cpp
Description: 由于切换后工具栏的位置没有及时刷新,及部分关键日志
Log: 修复当从截图录屏按钮切换至截图按钮时，默认选中了直线按钮
Bug: https://pms.uniontech.com/bug-view-181299.html
=> fix: 修复当从截图录屏按钮切换至截图按钮时，默认选中了直线按钮

src/waylandrecord/waylandintegration.cpp
Description: 由于双屏扩展模式下，使用buffer之后窗管没有去释放，现在交由应用主动去释放
Log: 适配窗管新接口，保证每次使用buffer之后，都可以被释放
Bug: https://pms.uniontech.com/bug-view-191041.html
=> fix: 适配窗管新接口，保证每次使用buffer之后，都可以被释放

src/waylandrecord/waylandintegration.cpp, src/waylandrecord/waylandintegration_p.h
Description: 在m900上，没有走hw的编码流程，导致录屏无法结束
Log: 修复m900无法录屏的问题，适配m900/Backspace无法删除已选中图形
Bug: https://pms.uniontech.com/bug-view-187823.htm
=> fix: 修复m900无法录屏的问题，适配m900

src/camera/majorimageprocessingthread.cpp, src/main_window.cpp, src/widgets/zoomIndicator.cpp
Description: 由于opengl窗口的server不存在，导致程序退出
Log: 修复点击滚动截图后，截图录屏自动退出
Bug: https://pms.uniontech.com/bug-view-190933.html
=> fix: 修复点击滚动截图后，截图录屏自动退出

src/record_process.cpp, src/waylandrecord/avoutputstream.cpp, src/waylandrecord/recordadmin.cpp, src/waylandrecord/waylandintegration.cpp, src/waylandrecord/waylandintegration_p.h
Description: 由于双屏扩展模式下，使用buffer之后窗管没有去释放，现在交由应用主动去释放，需要减少处理buffer的时间，以免冗余
Log: 适配窗管接口,修改处理buffer的流程，避免该流程耗时太长
Bug: https://pms.uniontech.com/bug-view-191041.html
=> fix: 适配窗管接口,修改处理buffer的流程，避免该流程耗时太长

src/utils/audioutils.cpp
Description: 在玲珑环境下沙盒内部无法无法执行pacmd命令进行声源查询，需要使用pactl命令
Log: 修复截图录屏文件未进行保存
Bug: https://pms.uniontech.com/bug-view-185915.html
=> fix: 修复截图录屏文件未进行保存

src/src.pro, src/waylandrecord/waylandintegration.cpp, src/waylandrecord/waylandintegration_p.h
Description:  1055上窗管将buffer release接口放开了，需要应用主动调用
Log: 兼容性适配，在105x分支上，1055与窗管有强依赖，需要进行隔离
=> chore: 兼容性适配，在105x分支上，1055与窗管有强依赖，需要进行隔离

src/pin_screenshots/ui/subtoolwidget.cpp
Description: 初始化贴图工具栏时没有更新配置
Log: 修复贴图保存到剪切板，通知提示“保存失败”
=> fix: 修复贴图保存到剪切板，通知提示“保存失败”

src/src.pro, src/waylandrecord/waylandintegration.cpp
Description: 1055上窗管将buffer release接口放开了，需要应用主动调用
Log: 兼容性适配，在主线分支上，1055及以上与窗管有强依赖，需要进行隔离
=> chore: 兼容性适配，在主线分支上，1055及以上与窗管有强依赖，需要进行隔离

src/dde-dock-plugins/recordtime/recordtimeplugin.cpp, src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/recordtime/timewidget.h
Description: 由于录屏计时插件的item widget高度不正确导致
Log: 修复任务栏设置在侧边，录屏计时图标大小不正确的问题
Bug: https://pms.uniontech.com/bug-view-200953.html
https://pms.uniontech.com/bug-view-200663.html
https://pms.uniontech.com/bug-view-194037.html
=> fix: 修复任务栏设置在侧边，录屏计时图标大小不正确的问题

src/button_feedback.cpp, src/button_feedback.h
Description: 由于2d模式（无窗口特效）不支持透明，因此会将背景框显示出来
Log: 修复录屏选择可见点击效果，录屏中点击鼠标，显示黑色背景
Bug: https://pms.uniontech.com/bug-view-200881.html
=> fix: 修复录屏选择可见点击效果，录屏中点击鼠标，显示黑色背景

src/dde-dock-plugins/shotstart/iconwidget.cpp, src/dde-dock-plugins/shotstart/iconwidget.h, src/dde-dock-plugins/shotstart/shotstartplugin.cpp, src/dde-dock-plugins/shotstart/shotstartplugin.h
Description: 插件图标及文字是应用绘制的，现改为dock绘制
Log: 修复高分屏机器，分辨率调整为2.25时，‘截图录屏’图标在快捷面版中显示异常
Bug: https://pms.uniontech.com/bug-view-200865.html
=> fix: 修复高分屏机器，分辨率调整为2.25时，‘截图录屏’图标在快捷面版中显示异常

src/main_window.cpp, src/main_window.h
Description: 由于开始录屏之前，就会将需要录制的屏幕大小给进去，录制过程中，不允许修改分辨率
Log: 录屏时不允许改变屏幕分辨率
=> fix: 录屏时不允许改变屏幕分辨率

src/widgets/shapeswidget.cpp, src/widgets/shapeswidget.h
Description: 在端点没有计算偏移量
Log: 修复截图编辑箭头和直线，光标在端点区域的显示不正确
Bug: https://pms.uniontech.com/bug-view-202239.html
=> fix: 修复截图编辑箭头和直线，光标在端点区域的显示不正确

src/dde-dock-plugins/recordtime/timewidget.cpp
Description: 由于返回的item高度不正确导致
Log: 修复任务栏高度调整到最高并设置在左侧，进行录屏操作，录屏图标显示异常
Bug: https://pms.uniontech.com/bug-view-203933.html
=> fix: 修复任务栏高度调整到最高并设置在左侧，进行录屏操作，录屏图标显示异常

src/main_window.cpp, src/widgets/subtoolwidget.cpp, src/widgets/subtoolwidget.h, src/widgets/toolbar.cpp, src/widgets/toolbar.h
Description: 修复点击滚动截图选项菜单中的选项会触发自动滚动功能
Log: 修复点击滚动截图选项菜单中的选项会触发自动滚动功能
Bug: https://pms.uniontech.com/bug-view-199335.html
=> fix: 修复点击滚动截图选项菜单中的选项会触发自动滚动功能

src/pin_screenshots/ui/subtoolwidget.cpp, src/pin_screenshots/ui/subtoolwidget.h, src/widgets/subtoolwidget.cpp, src/widgets/subtoolwidget.h
Description: 修复截图指定保存位置，hover到历史保存位置后，移动到“保存时更新位置”选项时，hover未消失
Log: 修复截图指定保存位置，hover到历史保存位置后，移动到“保存时更新位置”选项时，hover未消失
Bug: https://pms.uniontech.com/bug-view-189167.html
=> fix: 修复截图指定保存位置，hover到历史保存位置后，移动到“保存时更新位置”选项时，hover未消失

src/countdown_tooltip.cpp, src/countdown_tooltip.h, src/main_window.cpp, src/record_process.cpp, src/record_process.h
Description: 快捷全屏录制时，屏蔽3s倒计时，通知消息，及捕捉区域边框
Log: 快捷全屏录制时，屏蔽3s倒计时，通知消息，及捕捉区域边框
Bug: https://pms.uniontech.com/bug-view-213709.html
=> fix: 快捷全屏录制时，屏蔽3s倒计时，通知消息，及捕捉区域边框

src/main_window.cpp, src/main_window.h, src/widgets/toptips.cpp, src/widgets/toptips.h
Description: 快捷全屏录制时，不显示左上角捕捉区域大小提示、不画窗口的黑色背景
Log: 快捷全屏录制时，不显示左上角捕捉区域大小提示、不画窗口的黑色背景
Bug: https://pms.uniontech.com/bug-view-213709.html
=> fix: 快捷全屏录制时，不显示左上角捕捉区域大小提示、不画窗口的黑色背景

src/main_window.cpp
Description: 修复截图设置保存时设置位置，在锁屏页面截图，进入系统，关闭截图保存操作框，会闪现锁屏页面
Log: 修复截图设置保存时设置位置，在锁屏页面截图，进入系统，关闭截图保存操作框，会闪现锁屏页面
Bug: https://pms.uniontech.com/bug-view-213977.html
=> fix: 修复截图设置保存时设置位置，在锁屏页面截图，进入系统，关闭截图保存操作框，会闪现锁屏页面

src/main_window.cpp
Description: 由于华为云2d模式不支持透明模式，需要将透明属性屏蔽
Log: 修复华为云平台上截图编辑模式》文字输入，输入一个字母会出现多相同字母
Bug: https://pms.uniontech.com/bug-view-218923.html
=> fix: 修复华为云平台上截图编辑模式》文字输入，输入一个字母会出现多相同字母

src/main_window.cpp
Description: 修复截图保存时设置位置，在锁屏页面截图，进入系统，保存截图，会闪现锁屏页面
Log: 修复截图保存时设置位置，在锁屏页面截图，进入系统，保存截图，会闪现锁屏页面
Bug: https://pms.uniontech.com/bug-view-213977.html
=> fix: 修复截图保存时设置位置，在锁屏页面截图，进入系统，保存截图，会闪现锁屏页面

src/dde-dock-plugins/recordtime/timewidget.cpp
Description: 修复录屏时，调整插件区域录屏图标顺序，录屏直接结束
Log: 修复录屏时，调整插件区域录屏图标顺序，录屏直接结束
Bug: https://pms.uniontech.com/bug-view-215503.html
=> fix: 修复录屏时，调整插件区域录屏图标顺序，录屏直接结束

src/main_window.cpp, src/main_window.h
Description: 由于DDE更新了电源管理界面的dbus信号，需要应用重新适配
Log: 修复电源界面进行截图->工具菜单里的“选项”功能未禁用
Bug: https://pms.uniontech.com/bug-view-222335.html
=> fix: 修复电源界面进行截图->工具菜单里的“选项”功能未禁用

src/main_window.cpp
Description: 录制视频时选择显示点击，录屏过程中点击多任务视图，结束录屏后，键盘无法正常使用
Log: 录制视频时选择显示点击，录屏过程中点击多任务视图，结束录屏后，键盘无法正常使用
Bug: https://pms.uniontech.com/bug-view-227399.html
https://pms.uniontech.com/bug-view-227375.html
=> fix: 录制视频时选择显示点击，录屏过程中点击多任务视图，结束录屏后，键盘无法正常使用

src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/recordtime/timewidget.h, src/dde-dock-plugins/shotstart/shotstartplugin.cpp
Description: 当前用户在.cache目录下无权限时，不采用文件共享的方式来停止录屏，而是直接发送停止的dbus信号
Log: 修复录屏时点击计时图标没有退出录屏
Bug: https://pms.uniontech.com/bug-view-231153.html
=> fix: 修复录屏时点击计时图标没有退出录屏

src/button_feedback.cpp
Description: 穿透效果已经在父窗口中实现，子窗口不用设置穿透
Log: 修复截图录屏选择区域进行截图时右下角闪屏
Bug: https://pms.uniontech.com/bug-view-231035.html
https://pms.uniontech.com/bug-view-231041.html
=> fix: 修复截图录屏选择区域进行截图时右下角闪屏

src/waylandrecord/waylandintegration.cpp, src/waylandrecord/waylandintegration_p.h
Description: 由于kwayland的buffer没有正常释放，现在将buffer数据的拷贝单独放到一个线程中进行
Log: 修复wayland下双屏录制时出现系统崩溃的情况
Bug: https://pms.uniontech.com/bug-view-210933.html
=> fix: 修复wayland下双屏录制时出现系统崩溃的情况

src/main_window.cpp
Description: 截图的区域没有将缩放比例带入计算
Log: 修复滚动截屏时 图片预览右侧多出虚线
Bug: https://pms.uniontech.com/bug-view-231759.html
=> fix: 修复滚动截屏时 图片预览右侧多出虚线

src/main_window.cpp
Description: 截图的区域没有将缩放比例带入计算
Log: 修复滚动截屏时,自动调整捕捉区域图片预览右侧多出虚线
Bug: https://pms.uniontech.com/bug-view-231759.html
=> fix: 修复滚动截屏时,自动调整捕捉区域图片预览右侧多出虚线

src/main_window.cpp, src/main_window.h
Description: 截图的区域没有将缩放比例带入计算
Log: 修复滚动截屏时,图片预览上侧多出虚线
Bug: https://pms.uniontech.com/bug-view-231759.html
=> fix: 修复滚动截屏时,图片预览上侧多出虚线

src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/recordtime/timewidget.h
Description: 由于1070上dock的风格改变，不再需要黑色背景，因此录屏插件需要适配
Log: 修复正常录屏中时，录屏插件图标在任务栏的插件区默认还有底色区域，与新插件图标风格不一致
Bug: https://pms.uniontech.com/bug-view-232619.html
=> fix: 修复正常录屏中时，录屏插件图标在任务栏的插件区默认还有底色区域，与新插件图标风格不一致

debian/control
procps 源码升级后，构建出的软件包名改动，https://github.com/deepin-community/procps/commit/56f2908bc078821a3c4968f8900bd95bfa3e119e#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0
Log: fix dependency
=> fix: Fix dependency libprocps dev to libproc2 dev

src/waylandrecord/avinputstream.cpp
Description: 由于ffmpeg读取音频数据的接口在USB耳机拔了之后给的返回值不正常，但是截图录屏中对不正常的返回值未进行数据的释放 操作，导致内存空间不断增大，造成系统卡死。
Log: 修复录制全屏，拔出USB耳机，一段时间后视频逐渐卡顿，最后系统卡死
Bug: https://pms.uniontech.com/bug-view-235371.html
=> fix: 修复录制全屏，拔出USB耳机，一段时间后视频逐渐卡顿，最后系统卡死

src/main_window.cpp
Description: 此方案是规避方案，在将数据传递到剪切板时，延时3s钟，确保数据完全传递到剪切板之后，截图录屏应用才退出。增加系统限定范 围及数据传递到剪切板时隐藏主界面。
Log: 修复双屏跨屏全屏截图，无法保存到剪切板,增加系统限定范围
Bug: https://pms.uniontech.com/bug-view-237073.html
=> fix: 修复双屏跨屏全屏截图，无法保存到剪切板,增加系统限定范围

3rdparty/displayjack/wayland_client.h, src/main_window.cpp, src/main_window.h, src/src.pro
Description: Since the window tube abandoned the previous window to get window information in 1070, it needs to adapt the interface to get the latest window information
Log: New interface that adapts window tube to obtain window information.
Bug: https://pms.uniontech.com/bug-view-235511.html
=> fix: New interface that adapts window tube to obtain window information.

src/dde-dock-plugins/recordtime/timewidget.cpp
Description: 由于1070新图标适配，图标大小改变，需要对点击范围做对应调整
Log: 修复任务栏在左右两侧时，点击录屏计时图标无法结束录屏
Bug: https://pms.uniontech.com/bug-view-240571.html
=> fix: 修复任务栏在左右两侧时，点击录屏计时图标无法结束录屏

src/main_window.cpp, src/main_window.h
Description: 由于图片数据传递到剪切板的速度太慢（图片数据越大，传递时间越久），因此在应用退出时数据还未传递完成，应用退出就会导致数 据传递中断，最终就会体现剪切板中没有对应图片数据
Log: 修复1070上x11和wayland概率性无法保存到剪切板
Bug: https://pms.uniontech.com/bug-view-237073.html
=> fix: 修复1070上x11和wayland概率性无法保存到剪切板

src/main_window.cpp
Description: 由于1070上窗管对焦点的管理更加严格，不会对全屏无焦点窗口自动设置焦点，因此在1070上截图录屏无焦点时将无法获取键 盘事件。
Log: 修复使用快捷键打开截图录屏时，无法使用ESC退出
Bug: https://pms.uniontech.com/bug-view-241263.html
=> fix: 修复使用快捷键打开截图录屏时，无法使用ESC退出

src/main_window.cpp, src/main_window.h
Description: 由于工具栏的定位点参考捕捉区域的左上角，因此会出现工具栏显示在屏幕外部。注意：双屏扩展两个屏幕大小不一致或者错位排布 时，此时捕捉区域是允许移动到屏幕外部。因为工具栏的定位点参考捕捉区域的左上角，此时就需要考虑两个方面。1.当捕捉区域左上角移动到屏幕边缘，工具栏左对齐捕捉区域。2. 当捕捉区域左上角移动到屏幕外，工具栏采用上次的位置进行显示。
Log: 修复双屏时，边缘截图无菜单显示
Bug: https://pms.uniontech.com/bug-view-242535.html
=> fix: 修复双屏时，边缘截图无菜单显示

src/dde-dock-plugins/shotstart/quickpanelwidget.cpp
Description: 优化截图录屏在快捷面板中tooltip的显示，名称显示不全时才会hover tooltip
Log: 优化截图录屏在快捷面板中tooltip的显示
Bug: https://pms.uniontech.com/bug-view-243721.html
=> fix: 优化截图录屏在快捷面板中tooltip的显示

src/pin_screenshots/main.cpp, src/pin_screenshots/ui/toolbarwidget.cpp
Description: 修复v23贴图工具栏在高缩放比下，工具栏模糊及选项按钮显示不全
Log: 修复v23贴图工具栏在高缩放比下，工具栏模糊及选项按钮显示不全
Bug: https://pms.uniontech.com/bug-view-219447.html
https://pms.uniontech.com/bug-view-230457.html
=> fix: 修复v23贴图工具栏在高缩放比下，工具栏模糊及选项按钮显示不全

src/main_window.cpp, src/main_window.h
Description: 同步主线提交29d68826cf1c5fef9afc288e80d717311272c7f0到当前分支
Log: 添加应答信号，以保证图片数据量太大时，无法保存到剪切板的问题
Bug: https://pms.uniontech.com/bug-view-246613.html
=> fix: 添加应答信号，以保证图片数据量太大时，无法保存到剪切板的问题

src/dde-dock-plugins/shotstartrecord/res.qrc, src/dde-dock-plugins/shotstartrecord/res/shot-start-record-plugin-dark.svg, src/dde-dock-plugins/shotstartrecord/res/shot-start-record-plugin.svg, src/dde-dock-plugins/shotstartrecord/shotstartrecord.pro, translations/deepin-screen-recorder_bo.ts, translations/deepin-screen-recorder_ug.ts, translations/deepin-screen-recorder_zh_CN.ts, translations/deepin-screen-recorder_zh_HK.ts, translations/deepin-screen-recorder_zh_TW.ts
1. 修复翻译问题
2. 更新在控制中心显示的图标,截图的默认图标在dcc-dock-plugin 插件中已有，录屏图标需单独安装
Log: 修复翻译和显示问题
=> fix: Wrong translation and icon in control-center

src/dde-dock-plugins/shotstart/shotstartplugin.cpp, src/dde-dock-plugins/shotstartrecord/quickpanelwidget.cpp, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
1. 截图托盘图标在录屏崩溃后仍保持禁用状态,回退之前的修改, 保留检测录屏正在进行中的代码
2. 调整日志等级并添加日志分类,以方便后端过滤日志数据
Log: 修复界面显示问题
=> fix: Screenshot tray icon remains disabled after recorder crash.

src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.h
保持托盘图标之前的状态，在录屏结束后
不一定需要显示托盘图标。
Log: 修复部分显示问题
=> fix: Keep tray icon previous state

src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/recordtime/timewidget.h, src/dde-dock-plugins/shotstartrecord/com.deepin.dde.dock.module.shot-start-record-plugin.gschema.xml
之前的提交将 gschema 配置文件设置为false, 不会显示
任何菜单，调整文件配置。
Log: 修复托盘图标菜单问题
Bug: https://pms.uniontech.com/bug-view-250811.html
调整宽度计算值为1070的推荐值，同时回退之前设置
最小宽度的修改，修复图标显示过程中变更宽度的问题
Log: 修复图标显示问题
Bug: https://pms.uniontech.com/bug-view-250749.html
=> fix: Task trayicon widget error

debian/changelog
Bump version to 5.12.20
PR:
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/459
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/465
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/466
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/467
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/468
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/469
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/470
* https://github.com/linuxdeepin/deepin-screen-recorder/pull/471
Log: Bump version to 5.12.20
=> chore: Bump version to 5.12.20

com.deepin.ScreenRecorder.service, com.deepin.Screenshot.service, src/record_process.cpp
taskbar bug
fix: [UI] fix shortcut evoke screen-recorder bug and displayed on the taskbar bug
The icon for repairing screenshots will be displayed on the taskbar for more than 5 seconds before disappearing from bug. Fix the failure to use shortcut keys to evoke screenshots in 6.0.1deb format.
Log: The icon for repairing screenshots will be displayed on the taskbar for more than 5 seconds before disappearing from bug. Fix the failure to use shortcut keys to evoke screenshots in 6.0.1deb format.
Bug: https://pms.uniontech.com/bug-view-251835.html https://pms.uniontech.com/bug-view-250323.html
=> fix: [UI] fix shortcut evoke screen-recorder bug and displayed on the

src/main_window.cpp, src/pin_screenshots/mainwindow.cpp
相机调整为在录屏时初始化,截图时无需调用
Log: 调整应用初始化处理
旧版保存了图片的原始数据，在数据较大时对后端
剪贴板有影响。调整为使用转换PNG格式数据，降低
后端转换影响。
Log: 修改剪贴板无记录问题
Bug: https://pms.uniontech.com/bug-view-251565.html
=> fix: 调整相机初始化和修复剪贴板无数据问题

src/widgets/shapeswidget.cpp
截图时，编辑多行文字，完成截图后，插入的文字为居中显示问题
保存和显示不一致问题
Log: 修改截图编辑多行文字保存对齐问题
Bug: https://pms.uniontech.com/bug-view-256283.html
=> fix: 修改截图编辑多行文字保存对齐问题

src/waylandrecord/waylandintegration.cpp
fix the blurry screen of video recorded by a wayland machine
Log: fix the blurry screen of video recorded by a wayland machine
Bug: https://pms.uniontech.com/bug-view-249005.html
=> fix: blurry screen of video recorded error

src/pin_screenshots/mainwindow.cpp
截屏贴图-触发贴图后滑动鼠标滚轮缩放，窗口不能超出屏幕
Log:  截屏贴图-触发贴图后滑动鼠标滚轮缩放，窗口不能超出屏幕
Bug: https://pms.uniontech.com/bug-view-254799.html
=> fix: 贴图不能移动出屏幕

src/main_window.cpp
When the calendar is reminded, the screenshot is taken and the toolbar is not set at the top.
Log: When the calendar is reminded, the screenshot is taken and the toolbar is not set at the top.
Bug: https://pms.uniontech.com/bug-view-254705.html
=> fix: the window incorrect layer

src/dde-dock-plugins/recordtime/timewidget.cpp
The dock plug-in is not vertically centered.
Log: The dock plug-in is not vertically centered.
Bug: https://pms.uniontech.com/bug-view-259787.html
=> fix: The dock plug-in is not vertically centered

src/dde-dock-plugins/shotstart/quickpanelwidget.cpp, src/dde-dock-plugins/shotstartrecord/quickpanelwidget.cpp
The font size of the system is set to the largest, and some of the text in the shortcut panel is incomplete.
Log: The quick panel plugin not show correct.
Bug: https://pms.uniontech.com/bug-view-260963.html
=> fix: The quick panel plugin not show correct

src/record_process.cpp
fix the recorded gif has a grid block shadow.
use the color palette optimization.
Log: fix the recorded gif has a grid block shadow.
Bug: https://pms.uniontech.com/bug-view-262443.html
=> fix: the recorded gif has a grid block shadow

src/dde-dock-plugins/shotstart/shotstartplugin.cpp, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp
Fix compile error: duplicate macro definition,
QUICK_ITEM_KEY defined in dde-dock.
Log: fix complie error
=> fix: compile error

com.deepin.ScreenRecorder.service, com.deepin.Screenshot.service, src/record_process.cpp
taskbar bug
The icon for repairing screenshots will be displayed on the taskbar for more than 5 seconds before disappearing from bug. Fix the failure to use shortcut keys to evoke screenshots in 6.0.1deb format.
Log: The icon for repairing screenshots will be displayed on the taskbar for more than 5 seconds before disappearing from bug. Fix the failure to use shortcut keys to evoke screenshots in 6.0.1deb format.
Bug: https://pms.uniontech.com/bug-view-251835.html https://pms.uniontech.com/bug-view-250323.html
cherry-pick from 8eb411ca3656d4dda31858d34eaa1bb789e49312 (https://github.com/linuxdeepin/deepin-screen-recorder/pull/475)
=> fix: [UI] fix shortcut evoke screen-recorder bug and…… (#475)

src/main_window.cpp
hide the file path after the screenshot is completed.
Log: hide the file path after the screenshot is completed.
Task: https://pms.uniontech.com/task-view-356211.html
=> feat: hidden the storage path

src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/recordtime/timewidget.h
During screen recording, the system time was modified, 
and the screen recorthe taskbar was displayed incorrectly
Log: the temporal performance of recording gif
Bug: https://pms.uniontech.com/bug-view-258049.html
https://pms.uniontech.com/bug-view-258049.html
=> fix: the taskbar display incorrectly

src/main_window.cpp, src/record_process.cpp, translations/deepin-screen-recorder_zh_CN.ts
hide the file path after the screenshot is completed.
Log: hide the file path after the screenshot is completed.
Task: https://pms.uniontech.com/task-view-356211.html
=> fix: fix the new notice style

src/record_process.cpp
After discussion, we still use the color palette to ensure the effect.
Log: fix the grid block shadow in recorded gif.
Bug: https://pms.uniontech.com/bug-view-264145.html
https://pms.uniontech.com/bug-view-262443.html
=> fix: the grid block shadow in recorded gif

src/main_window.cpp
Adjust the time sequence of the screenshot completion prompt
Log: Adjust the time sequence of the screenshot completion prompt
Bug: https://pms.uniontech.com/bug-view-266109.html
=> fix: Adjust the time sequence of the screenshot completion prompt

src/main_window.cpp
Log: 修复外接4K屏卡顿不流畅，使用update去更新界面而不是repaint
Bug：https://pms.uniontech.com/bug-view-255835.html
=> fix: 外接4K屏卡顿不流畅

src/dde-dock-plugins/shotstart/tipswidget.cpp, src/dde-dock-plugins/shotstartrecord/tipswidget.cpp
remove the margins from the dock plugin tooltips, which will be managed uniformly by the dock
Issue: https://github.com/linuxdeepin/developer-center/issues/9997
=> feat: remove the inner margin of dock plugin tooltips

src/main_window.cpp
fix Default window screenshot in dual-screen extension mode,
and the screenshot border is extended to another screen
Log: the select screenshot border display problem
Bug: https://pms.uniontech.com/bug-view-265991.html
=> fix: the select screenshot border display problem

src/dde-dock-plugins/shotstart/iconwidget.cpp
Log: the screen-capture icon in the taskbar
Bug:https://pms.uniontech.com/bug-view-266991.html 
Issue:https://github.com/linuxdeepin/developer-center/issues/10072
=> fix: the screen-capture icon in the taskbar

src/main_window.cpp
在保存时，不响应 ECS 事件。
防止 exitApp 导致 QProcess 被提前释放
Issues: linuxdeepin/developer-center#10385
=> fix: fix a crash

src/dde-dock-plugins/recordtime/recordtimeplugin.cpp, src/dde-dock-plugins/recordtime/timewidget.cpp, src/dde-dock-plugins/recordtime/timewidget.h
fix the status bar display error time
Log: fix the status bar display error time
Bug: https://pms.uniontech.com/bug-view-262791.html
=> fix: the status bar display error time

src/dde-dock-plugins/recordtime/timewidget.cpp
Log: fix the recorder taskbar incorrect foreground-color
Bug: https://pms.uniontech.com/bug-view-268895.html
=> fix: the recorder taskbar incorrect foreground-color

src/main_window.cpp
Log: fix the Alt+Print shotcut get the wrong image
Bug: https://pms.uniontech.com/bug-view-267329.html
=> fix: the Alt+Print shotcut get the wrong image

src/utils.cpp, src/utils/audioutils.cpp, src/waylandrecord/avinputstream.cpp, src/waylandrecord/waylandintegration.cpp
Optimize command line acquisition parameters
Log: Optimize command line acquisition parameters
Task: https://pms.uniontech.com/task-view-362613.html
=> fix: Optimize command line acquisition parameters

src/main_window.cpp
fix the mouse click control lose in workspace
Log: fix the mouse click control lose in workspac
Bug: https://pms.uniontech.com/bug-view-268293.html
=> fix: the mouse click control lose in workspace

src/main.cpp
fix the dual screen expandsion position when scaled
Log: fix the dual screen expandsion position when scaled
Bug: https://pms.uniontech.com/bug-view-273083.html
=> fix: the dual screen expandsion position when scaled

debian/changelog, src/event_monitor.cpp, src/record_process.cpp, src/record_process.h, src/utils.h, src/utils/audioutils.cpp, src/utils/configsettings.cpp, src/waylandrecord/avoutputstream.cpp, src/waylandrecord/recordadmin.cpp, src/waylandrecord/waylandintegration_p.h
[fix: audio record pts error on wayland](https://github.com/linuxdeepin/deepin-screen-recorder/commit/734f5279a0727966fed0bf7fa2b6c731ec5d02d7) 
The recorded audio enumeration type is inconsistent.
The backend processing has incorrect set values,
Causes audio recording errors.
Log: Fix audio record error.
[chore: Bump version to 6.5.0](https://github.com/linuxdeepin/deepin-screen-recorder/commit/c976db349e1d5ed5bf20feceac329aa121955a0e) 
Bump version to 6.5.0
Log: Bump version to 6.5.0
=> Fix  record error and bump verison

src/main_window.cpp
fix the 'alt print' shotcut not quit
Log: fix the 'alt print' shotcut not quit
Bug: https://pms.uniontech.com/bug-view-279221.html
=> fix: the 'alt print' shotcut not quit

src/dde-dock-plugins/shotstart/shotstartplugin.cpp, src/dde-dock-plugins/shotstart/shotstartplugin.h, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.h
As title.
Tray icon manager updated from dde-dock to dde-tray-loader, no longer compatible with previous settings.
This commit updates the interface to PluginsItemInterfaceV2.
Log: Adapt new quick pannel plugin interface.
Bug: https://pms.uniontech.com/bug-view-266839.html
=> fix: adapt new quick pannel plugin interface

src/record_process.cpp
- Change -vf to -filter_complex to support more complex filter chains
- Update palettegen parameters to use stats_mode=diff mode
- Optimize paletteuse parameters by adding:
- bayer dithering algorithm
- bayer_scale=5
- rectangle diff mode
- These changes improve GIF output quality and color fidelity
Log: Optimize GIF conversion filter parameters
Bug: https://pms.uniontech.com/bug-view-291463.html
Influence: save-gif
=> fix: Optimize GIF conversion filter parameters

src/dde-dock-plugins/shotstart/iconwidget.cpp, src/dde-dock-plugins/shotstartrecord/recordiconwidget.cpp, src/record_process.cpp
[fix: Optimize GIF conversion filter parameters](https://github.com/linuxdeepin/deepin-screen-recorder/commit/33e796cbbf3158a2812e37c938fbd77d0d341c7a) 
- Change -vf to -filter_complex to support more complex filter chains
- Update palettegen parameters to use stats_mode=diff mode
- Optimize paletteuse parameters by adding:
- bayer dithering algorithm
- bayer_scale=5
- rectangle diff mode
- These changes improve GIF output quality and color fidelity
Log: Optimize GIF conversion filter parameters
Bug: https://pms.uniontech.com/bug-view-291463.html
[fix: tray icon incorrect](https://github.com/linuxdeepin/deepin-screen-recorder/commit/2373caaa18f2bb08505cdeb6b2dd4b905732b7a2) 
The tray icon updated but not fully tested,
we are temporarily disable the new icon label.
Resume later.
Log: Fix …
=> fix: GIF conversion and tray icon

src/main_window.cpp
As title.
Log: Fix ocr disappearing in treeland.
Bug: https://pms.uniontech.com/bug-view-283631.html
=> fix: ocr disappears in treeland

src/dde-dock-plugins/recordtime/timewidget.cpp
- Removed unnecessary checks for left button press and hover state in mouseReleaseEvent.
- Streamlined the event handling logic to improve code readability and maintainability.
This change enhances the clarity of the mouse event handling in the TimeWidget class. Log: Simplify mouse release event handling in TimeWidget Bug: https://pms.uniontech.com/bug-view-297809.html
=> fix: Simplify mouse release event handling in TimeWidget

src/main.cpp, src/main_window.cpp, src/widgets/subtoolwidget.cpp
[fix: Fix save path settings in screenshot toolbar](https://github.com/linuxdeepin/deepin-screen-recorder/commit/86706add3c1a17bf76957c4b9dd7687a26b9b07a) 
Description:
- Remove toolbar visibility debug log
- Add clipboard save option back to save options group
Log: Fix screenshot toolbar save path settings
Bug: https://pms.uniontech.com/bug-view-298655.html
[fix: Use QProcess as workaround for scale factor](https://github.com/linuxdeepin/deepin-screen-recorder/commit/6ad6cdaeccd62aa2c7f2cbaef38971cab1580837) 
Description:
- dbus-send return "No such object path" on the first call
- Replace QDBusInterface with QProcess to get display scale factor
- Add TODO comment for future toolbar position calculation refactoring
Log: Fix screen recorder launch issue when called via dbus-send
Bug: …
=> fix: save path settings and scale factor

src/main.cpp, src/utils/borderprocessinterface.cpp
Adjust SVG center size and point parameters,
fix incomplete display of long and narrow images
when applying borders.
Log: Adjust border size parameters for narrow images
=> fix: adjust border size parameters for narrow images

src/main_window.cpp
fix the tooltips not show correct in left top position due to not recieve mouseMove event
Log: fix the tooltips not show correct in left top position
Bug: https://pms.uniontech.com/bug-view-245865.html
=> fix: the tooltips not show correct in left top position

src/main_window.cpp
fix the lagging issue with the text function in the image editor. 
due to on x64 platform, shapeswidget may not get the Qt mouse event.
Log: fix the lagging issue with the text function in the image editor.
Bug: https://pms.uniontech.com/bug-view-302745.html
=> fix: the lagging issue with the text function in the image editor.

src/waylandrecord/waylandintegration.cpp
when two screen not aligned recorder may not record
Log: fix when two screen not aligned recorder may not record
Bug: https://pms.uniontech.com/bug-view-298177.html
=> fix: when two screen not aligned recorder may not record

src/dde-dock-plugins/shotstart/iconwidget.cpp, src/dde-dock-plugins/shotstartrecord/recordiconwidget.cpp, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.cpp, src/dde-dock-plugins/shotstartrecord/shotstartrecordplugin.h
[fix: not hidden record tray icon when recoding](https://github.com/linuxdeepin/deepin-screen-recorder/commit/f8c12835b06b28d9cd49382535383ab50f2dbe73) 
The DBus interface has been changed, updated.
Log: hide record tray icon when recording.
Bug: https://pms.uniontech.com/bug-view-298541.html
[fix: tray icon is blurred when the scale factor exceeds 1](https://github.com/linuxdeepin/deepin-screen-recorder/commit/2f0a301bd37318a20877326b0f11ff99f4a071a8) 
Use QIcon::paint() replace QPixmap.
Log: fix a tray icon ui issue.
Bug: https://pms.uniontech.com/bug-view-298677.html
=> fix: hide record tray icon / ui issue

src/main_window.cpp
fix the lagging issue with the text function in the image editor. due to on x64, SW64, arm platform, shapeswidget may not get the Qt mouse event.
Log: fix the lagging issue with the text function in the image editor.
Bug: https://pms.uniontech.com/bug-view-302745.html
=> fix: the lagging issue in other platform.

debian/rules, src/main.cpp, src/main_window.cpp, src/main_window.h, src/pin_screenshots/ui/subtoolwidget.cpp, src/screenshot.cpp, src/screenshot.h
[fix: can not save pin screenshots settings](https://github.com/linuxdeepin/deepin-screen-recorder/commit/0e28ed6302d7bdc2cd3d39f73bbcb8e6c1da6002) 
As title.
Log: fix a config issue.
Bug: https://pms.uniontech.com/bug-view-298631.htm
[fix: can not start record via tray icon](https://github.com/linuxdeepin/deepin-screen-recorder/commit/9c72e143dd75267f39066395fbbd1b8949295a1f) 
- Fix zombie processes caused by stopRecord() misuse
- Restore original stopRecord() behavior to enable recording start
- Add stopApp() for proper process termination
- Prevent lingering processes when not recording
Log: fix can not start recrod via tray icon.
[chore: support parallel build](https://github.com/linuxdeepin/deepin-screen-recorder/commit/78935882c2f37537cc7b4b417b77de2cef95a66d) 
As title.
Log: …
=> fix: can not save pin screenshots settings / can not start record via tray icon

src/record_process.cpp, src/record_process.h
The `split` with `palettegen` using full frames,
Split into two steps, compress the number of frames used by the palette.
Log: fix a oom issue.
Bug: https://pms.uniontech.com/bug-view-308389.html
=> fix: oom when convert large video to gif

src/dde-dock-plugins/recordtime/recordtimeplugin.cpp, src/dde-dock-plugins/recordtime/recordtimeplugin.h, src/record_process.cpp
We log the record time to a file to avoid plugin crashes, but time is restored after reboot.
Reset the time every time when start a new screen recording.
Log: fix a ui issue.
Bug: https://pms.uniontech.com/zentao/bug-view-308411.html
[fix: improve the speed of convrting to GIF](https://github.com/linuxdeepin/deepin-screen-recorder/pull/638/commits/fa6c4144833deff48eb89374b532d5f9d6502fe2)
Fileter frames in `avfilter`.
Log: improve the speed of convrting to GIF.
Bug: https://pms.uniontech.com/zentao/bug-view-295949.html
=> fix: not reset time after reboot / improve the speed of convrting to GIF

src/main.cpp, src/main_window.cpp, src/src.pro, src/utils.cpp, src/utils.h, src/utils/x_multi_screen_info.cpp, src/utils/x_multi_screen_info.h
screen-recorder's theme type is the same as the current system settings.
Log: fix theme type error.
Bug: https://pms.uniontech.com/zentao/bug-view-300679.html
https://pms.uniontech.com/zentao/bug-view-287991.html
[fix: paint full screen rectangle error.](https://github.com/linuxdeepin/deepin-screen-recorder/pull/639/commits/6e64658a6d8d3bdaa20c82d1fd7a7d106f3b238e)
There is an error in the scale factor from the screen,
Force reset the scale factor before fix bug 205567.
Those changes for multi-screen, the coordinates of the screen
need to be flush on the horizontal or vertical axis.
Log: fix a ui issue.
Bug: https://pms.uniontech.com/zentao/bug-view-307017.html
=> fix: use system theme / reset scale in special multi screen

src/waylandrecord/waylandintegration.cpp
fix crush of the kwaylandclient version may not match the runtime and complile environment.
Log: fix crush of the kwaylandclient version may not match the runtime and complile environment
Bug: https://pms.uniontech.com/bug-view-304871.html
=> fix: crush of the kwaylandclient version difference.

debian/control, src/camera/majorimageprocessingthread.cpp, src/countdown_tooltip.cpp, src/dde-dock-plugins/shotstartrecord/quickpanelwidget.cpp, src/src.pro
As title, grab image rectangle erorr.
Previous commit incorrect.
Log: fix blur effect.
Bug: https://pms.uniontech.com/zentao/bug-view-309211.html
=> fix: blur effect error and revert previous commit

src/event_monitor.cpp
This reverts commit c0ba1f90d65e300390de66c82a7931c38fd35c7f. XCloseDisplay() also call XSync().
=> Revert "fix: replace XSync with XFlush"

src/event_monitor.cpp, src/main_window.h
- Adjust cleanup timing to avoid race with record thread
- Move cleanup logic to end of run method
- Add 30s timeout to prevent deadlock
Log: restructure event monitor cleanup.
Bug: https://pms.uniontech.com/bug-view-306357.html
=> fix: restructure event monitor cleanup

src/widgets/subtoolwidget.cpp
As title.
Log: enable gif on loong64/sw64/mips
Bug: https://pms.uniontech.com/zentao/bug-view-308909.html,
https://pms.uniontech.com/zentao/bug-view-309067.html
=> fix: enable gif on loong64/sw64/mips

src/main_window.cpp
fix toolbar position calcate incorrect in high dpi
Log: fix toolbar position calcate incorrect in high dpi
Bug: https://pms.uniontech.com//bug-view-311839.html
=> fix: toolbar position calcate incorrect in high dpi

src/dde-dock-plugins/shotstart/commoniconbutton.cpp, src/dde-dock-plugins/shotstartrecord/commoniconbutton.cpp, src/dde-dock-plugins/shotstartrecord/quickpanelwidget.cpp
- Introduced a constant `ICON_SIZE` for the icon dimensions to improve code readability and maintainability.
- Updated the fixed size and pixmap drawing to utilize this constant, ensuring consistency across the component.
=> fix: Use constant for icon size in CommonIconButton

src/main_window.cpp, src/main_window.h
Fixed an issue with Wayland window screenshots capturing the active window. Previously, it rigidly used the second-to-last layer method (which could capture input methods, notifications, or remote assistance windows). Now it references dde-dock's layer level and captures the window one layer above dde-dock.
Log: Fix active window detection in Wayland screenshots
Bug: https://pms.uniontech.com/bug-view-322949.html
=> fix: Fix Wayland window screenshot active window acquisition.

src/main_window.cpp
- Moved the showFullScreen() call to ensure the window is displayed in fullscreen mode during screenshot capture.
- Removed redundant showFullScreen() call to streamline the function.
Log: Adjust fullscreen handling for improved screenshot functionality.
bug: https://pms.uniontech.com/bug-view-318471.html
=> fix: Correct fullscreen behavior in screenshot functionality

src/main_window.cpp, src/main_window.h
Added dynamic wait time calculation function that adjusts clipboard save timeout according to image resolution, improving performance for small images while ensuring sufficient time for large images
Log: Implement adaptive clipboard wait time based on image size
Bug: https://pms.uniontech.com/bug-view-326039.html
=> fix: Optimize clipboard wait time based on image size

debian/changelog, translations.pri, translations/deepin-screen-recorder_lo.ts, translations/desktop/desktop_lo.ts
chore: Add new Lao translation file for deepin-screen-recorder
- Included deepin-screen-recorder_lo.ts in the translations list to support Lao language.
- This addition enhances localization efforts for a broader user base.
Log: Improve language support by adding Lao translation for the deepin-screen-recorder application.
=> chore: Add new Lao translation file for deepin-screen-recorder

debian/changelog, src/pin_screenshots/mainwindow.cpp, src/pin_screenshots/mainwindow.h, src/pin_screenshots/ui/subtoolwidget.cpp, src/pin_screenshots/ui/toolbarwidget.cpp, src/pin_screenshots/ui/toolbarwidget.h, src/widgets/subtoolwidget.cpp
fix: Enhance toolbar visibility management in MainWindow
- Introduced a new timer to manage the visibility of the toolbar, allowing it to hide after a short delay when the mouse leaves the main window.
- Added logic to check for visible menus before hiding the toolbar, ensuring it remains visible when menus are active.
- Refactored mouse event handling to improve toolbar display behavior during user interactions.
Log: Improve user experience by providing better control over toolbar visibility based on mouse activity.
bug: https://pms.uniontech.com/bug-view-327997.html
=> fix: Enhance toolbar visibility management in MainWindow

src/main.cpp, src/utils/screengrabber.cpp, src/utils/screengrabber.h
Improved the quickFullScreenshot function with retry mechanism and simplified save logic to prevent hanging during suspend/resume cycles. Key changes:
- Added 6-retry loop with 1s delay for KWin screenshot calls
- Unified save logic to always save to file and clipboard
- Enhanced path handling with dedicated Screenshots subdirectory
- Improved debug logging for troubleshooting
Log: Fix fullscreen screenshot hanging during S3/S4 state changes
Bug: @https://pms.uniontech.com/bug-view-328797.html
=> fix: Enhance fullscreen screenshot reliability in Wayland S3/S4 transitions

src/widgets/shapeswidget.cpp, src/widgets/shapeswidget.h
- Added handling for Delete and Backspace keys to delete the current shape.
- Implemented keyboard shortcuts for micro-adjustments of selected shapes using Ctrl and Shift modifiers.
- Improved movement logic for shapes using arrow keys and WASD keys, allowing for more intuitive control.
- Enhanced the adjustment logic for shapes of type "pen" and "effect" to maintain proportionality during resizing.
Log: Improve user experience in ShapesWidget by refining keyboard interactions for shape manipulation.
bug: https://pms.uniontech.com/bug-view-320491.html
=> fix: Enhance keyboard interaction for shape adjustments in ShapesWidget

src/src.pro, src/utils/timeutils.cpp, src/utils/timeutils.h, src/utils/utils.pri
add TimeUtils to get system time to avoid user change system get wrong time
Log: add TimeUtils to get system time
Bug: https://pms.uniontech.com/bug-view-268369.html
=> fix: add TimeUtils to get system time

src/waylandrecord/avinputstream.cpp, src/waylandrecord/avoutputstream.cpp
When adjusting the system time, the timestamp will change according to the system time change during the recording process, resulting in the problem of time jumping.
Log: adjust timestamp for audio stream.
Bug: https://pms.uniontech.com/bug-view-268369.html
=> fix: screen recording timestamp adjustment for audio stream.
